### ISSUE TITLE
Misc playtesting issues

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#193] opened 2017-07-16 17:00 UTC
Latest build from master:

- [x] Crash in HandleBuffs in Creature.cs:
{"Collection was modified; enumeration operation may not execute."}
on the line
foreach (Buff buff in Buffs)

- [x] Crash in Run in SearchFreeStockpileAct.cs:
GetNearestVoxel is returning null. i think this was when trying to build a new stockpile next to an existing one.

- [x] Crash sometimes when loading games in deserialize: looks like something to do with active crafting jobs?

- [x] Game still takes mouse inputs when not active window.

- [x] After a certain point, dropped resources (e.g. logs, dirt) can sometimes no longer be gathered. Dragging the gather tool over them does nothing. Possibly something to do with mining blocks under trees -> tree resources cannot be gathered. At that point, trees dwarves chop down will sometimes not automatically have their resources marked with the selection box for collection, and they cannot be manually gathered.

- [x] Dwarves sit around and starve themselves sometimes.

- [x] Dwarves no longer play sleep animations, instead standing in place if there are no beds, or repeatedly jumping on beds if there are (when mousing over, current action is teleport).

- [x] Not a bug, but why are textures no longer nearest-neighbor upscaled?

- [x] Crash in TextFieldLogic.cs on this line:
return Text.Substring(0, CursorPosition) + new String((char)Character, 1) + Text.Substring(CursorPosition, Text.Length - CursorPosition);
Out of range exception, text is "2" but CursorPosition is 2.

- [x] Mousing over fairies (spawned in god mode) crashes the game: 
DefaultOnMouseOver in DwarfSelectorTool.cs, line 188
sb.Append(dwarf.Stats.FullName + " (" + dwarf.Stats.CurrentClass.Name + ")");
dwarf is null.

- [x] Clicking on the button with the trinket icon (not the 'craft' button) crashes the game when there aren't enough resources to craft.
PlayState.cs line 992
data.SelectedResources = buildInfo.GetSelectedResources();
buildInfo is null.

 - [x] Start a new game. Cheat to create a workshop. Craft a wood trinket, then try to craft an iron trinket. The craftsdwarf will make two wood trinkets. Further orders to craft iron trinkets are ignored.

- [x] When there are too many crafting materials, materials at the bottom of the dropdown cannot be selected because tray buttons take priority.

- [x] Dwarves sometimes hoard objects in their inventories without ever putting them into stockpiles. If you tell them to gather a new object (in my case, an egg on the ground), they'll pick it up and throw one random object into the stockpile from their inventory (dirt in my case). Might be happening because miners went to sleep in the middle of a task before resuming?

- [x] Dwarves sometimes run back and forth between stockpile and logs from felled tree, picking up only one at a time before putting it in a stockpile - related to bug above?

- [ ] Top of screen sometimes not correctly showing counts of items across all stockpiles (trade screen seems to be accurate).

**Comment by mklingen** [comment] 2017-07-16 17:33
> Dwarves sit around and starve themselves sometimes.

Context please.

> Not a bug, but why are textures no longer nearest-neighbor upscaled?

Uh, they are!? What build? What branch? What are your specs? They definitely are nearest neighbor upscaled.

**Comment by mklingen** [comment] 2017-07-16 17:35
> Dwarves no longer play sleep animations, instead standing in place if there are no beds, or repeatedly jumping on beds if there are (when mousing over, current action is teleport).

Omg. you're right. I wonder what happened.

**Comment by plasticware** [comment] 2017-07-16 17:44
It seemed like the original miners I started with never fed themselves even though there was food in the stockpile (no chairs to sit on, but that didn't stop the other dwarves). Newer miners did not starve, but maybe if i'd waited another day they would have started starving too. I think their action was to get food from the stockpile, but they just stood around the balloon port and complained. Side note: should dwarves be suffering injuries (e.g. "dislocated left mustache") from starving damage? Any way to only make this happen in combat?

re: textures.
![scrn](https://user-images.githubusercontent.com/10678405/28249892-5c83d7fa-6a2c-11e7-900b-bcc458ea7c5c.png)

**Comment by mklingen** [comment] 2017-07-16 17:53
Okay, I think the texture filtering issue is due to an unsupported mip/mag filter mode I'm using. Will revert to a slightly uglier mode that is more likely to work.

**Comment by mklingen** [comment] 2017-07-16 18:11
RE: search free stockpile. This is caused by dwarfs trying to send items to a stockpile that hasn't been built yet.

**Comment by Blecki** [comment] 2017-07-17 23:01
Crash involving text field logic should be fixed on my branch.

**Comment by Blecki** [comment] 2017-07-18 00:05
> Clicking on the button with the trinket icon (not the 'craft' button) crashes the game when there aren't enough resources to craft.
> PlayState.cs line 992
> data.SelectedResources = buildInfo.GetSelectedResources();
> buildInfo is null.
> 
> Start a new game. Cheat to create a workshop. Craft a wood trinket, then try to craft an iron trinket. The craftsdwarf will make two wood trinkets. Further orders to craft iron trinkets are ignored, presumably because there isn't enough wood left for a third wood trinket.


Both fixed on my branch.

**Comment by mklingen** [comment] 2017-07-18 12:24
>Dwarves sometimes hoard objects in their inventories without ever putting them into stockpiles. If you tell them to gather a new object (in my case, an egg on the ground), they'll pick it up and throw one random object into the stockpile from their inventory (dirt in my case). Might be happening because miners went to sleep in the middle of a task before resuming?

> Dwarves sometimes run back and forth between stockpile and logs from felled tree, picking up only one at a time before putting it in a stockpile - related to bug above?

I bet I know what's happening. 

1. Dwarf fills inventory and gets a stock task
2. Stock task fails for whatever reason but the dwarf isn't told to retry
3. Dwarf's inventory (128 items) fills up so that there's only one slot left.
4. Dwarf uses the remaining slot to stock items, causing him/her to waltz back and forth between items and stockpile.

**Closed** 2017-08-04 17:49 UTC
Labels: bug, User-Experience
