### ISSUE TITLE
See through block

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#238] opened 2017-09-25 17:16 UTC
Version Master branch as of commit 6f0b258 
Found a block that has a side that can be seen through from one side. From all other visible sides, the block appears solid.
![dwarfcrop_seethrough_block](https://user-images.githubusercontent.com/3519989/30821316-3737a2b6-a225-11e7-9d31-55b4bba16383.PNG)
Corresponding save-files: [DwarfCorp.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1330238/DwarfCorp.zip)
Unfortunately, I cannot load the savegame (game crashes after "Loading Entities..."), but maybe you can load it.

**Comment by Aikhjarto** [comment] 2017-09-25 17:51
With `#define CREATE_CRASH_LOGS` to enable crash log for above save file, I get the following crash log
```
DwarfCorp Version 17.09.04_XNA
OS Version: 6.2.9200.0
OS Platform: Win32NT
OS SP: 
OS Version String: Microsoft Windows NT 6.2.9200.0
System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
Parametername: index
   bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   bei System.Collections.Generic.List`1.get_Item(Int32 index)
   bei DwarfCorp.Gui.VariableWidthFont.WordWrapString(String S, Single GlyphWidthScale, Single Width) in C:\Users\thomas\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Gui\Geo\VariableWidthFont.cs:Zeile 171.
   bei DwarfCorp.Gui.Widget.GetTextMesh(List`1 result) in C:\Users\thomas\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Gui\Widget.cs:Zeile 374.
   bei DwarfCorp.Gui.Widget.Redraw() in C:\Users\thomas\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Gui\Widget.cs:Zeile 363.
   bei DwarfCorp.Gui.Widget.GetRenderMesh() in C:\Users\thomas\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Gui\Widget.cs:Zeile 428.
   bei DwarfCorp.Gui.Widget.GetRenderMesh() in C:\Users\thomas\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Gui\Widget.cs:Zeile 430.
   bei DwarfCorp.Gui.Widget.GetRenderMesh() in C:\Users\thomas\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Gui\Widget.cs:Zeile 430.
   bei DwarfCorp.Gui.Root.Draw(Point Offset) in C:\Users\thomas\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Gui\Root.cs:Zeile 584.
   bei DwarfCorp.Gui.Root.Draw() in C:\Users\thomas\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Gui\Root.cs:Zeile 503.
   bei DwarfCorp.GameStates.LoadState.Render(DwarfTime gameTime) in C:\Users\thomas\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\LoadState.cs:Zeile 195.
   bei DwarfCorp.GameStates.GameStateManager.Render(DwarfTime time) in C:\Users\thomas\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\GameStateManager.cs:Zeile 149.
   bei DwarfCorp.DwarfGame.Draw(GameTime time) in C:\Users\thomas\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\DwarfGame.cs:Zeile 328.
   bei Microsoft.Xna.Framework.Game.DrawFrame()
   bei Microsoft.Xna.Framework.Game.Tick()
   bei Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   bei Microsoft.Xna.Framework.GameHost.OnIdle()
   bei Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   bei Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   bei System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.Run(Form mainForm)
   bei Microsoft.Xna.Framework.WindowsGameHost.Run()
   bei Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   bei Microsoft.Xna.Framework.Game.Run()
   bei DwarfCorp.Program.Main(String[] args) in C:\Users\thomas\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Program.cs:Zeile 72.
```

**Comment by mklingen** [comment] 2017-09-25 20:24
See through block is a duplicate of #232 , there was a regression there on ramp rebuilding. As for the crash, that's really bizarre. I will give it a look.

**Comment by mklingen** [comment] 2017-09-25 20:37
I believe the issue is caused by a german-specific unicode character getting into the string, wheras we were assuming ASCII-only. fix incoming.

**Comment by Blecki** [comment] 2017-09-25 20:49
For the see through block, I know I introduced at least one case involving slopes where the sides were not detected as being visible when I rewrote the geometry builder to use the super-fast slice method it uses now.. It only seems to happen on chunk seams and it's rare enough that I haven't been able to figure out what's causing it yet.

**Comment by Blecki** [comment] 2017-09-25 20:50
For the other; fix is in master for the release.

**Comment by Aikhjarto** [comment] 2017-09-25 21:03
Just tired latest master and get a different error:
`Loading failed: System.OverflowException: The value is too small or large for a single byte.
BoxConverter.cs Line 142`
I got this message in german in an ingame window. Thus, it's only a roughly translated excerpt and not the full stack trace.

**Comment by Aikhjarto** [comment] 2017-09-25 21:16
The in-game error message was a wall of text exceeding the game window. It would really benefit from a scrollbar and to ability to copy content as plain text.

**Comment by mklingen** [comment] 2017-09-25 21:41
Thanks so much for helping. this is very useful information.

**Comment by mklingen** [comment] 2017-09-25 21:50
Managed to get your file loading, many terrible things happening (dwarves all die immediately, cave creatures appearing in the sky, etc.) I unfortunately don't have time to fix this before release, but will look at patching it soon.

**Comment by mklingen** [comment] 2017-09-25 21:54
I think I know what's happening, believe it or not it's because your system is German! The values of floats getting read/written to the save files use the European style of "." vs "," for separators. Will make an effort unify locale for float reading/writing soon so that it doesn't depend on that.

**Comment by Blecki** [comment] 2017-09-25 21:58
Actually this should be as simple as a setting for newtonsoft.

**Comment by Blecki** [comment] 2017-09-25 22:00
You said separator not decimal. Never mind!

**Comment by Blecki** [comment] 2017-10-01 03:51
See through block - I believe this to be related to a race condition in the chunk rebuilder. We'll see if fixing that race condition fixes this error.

**Comment by Blecki** [comment] 2017-10-08 01:35
I've found the cause of this. The fix will take a bit.

**Comment by Blecki** [comment] 2017-10-08 20:51
Fixed.

**Closed by Blecki** 2017-10-08 20:51 UTC
Labels: bug, Graphics
