### ISSUE TITLE
Beds need rooms 2 high to sleep in

### ISSUE THREAD

**Issue by Vorgon1** [CompletelyFairGames/dwarfcorp#220] opened 2017-09-07 05:29 UTC
Maybe not a bug, but if you put a bed in a room that is only 1 block high, when a dwarf goes to sleep in the bed he flickers between the bed and the surface of the ground and on waking pops to the surface above the ground. Making the room 2 blocks high fixes the problem.

**Comment by mklingen** [comment] 2017-09-07 15:30
Reproduced, seems to be a bug with physics engine. Will make sure dwarf physics are turned off while they're sleeping.

**Comment by mklingen** [comment] 2017-09-07 22:39
fixed the issue with this commit: https://github.com/CompletelyFairGames/dwarfcorp/commit/517d4aa5e7f97c1faa2faa9432d8ee4705617924

Will be in the next build.

**Closed by mklingen** 2017-09-07 22:39 UTC
Labels: AI, bug
