### ISSUE TITLE
[Bug] Error saving on Linux (Fedora 27)

### ISSUE THREAD

**Issue by koenigjaeger** [CompletelyFairGames/dwarfcorp#463] opened 2017-11-16 16:08 UTC
Hi,

**Specs:**
Fedora 27 [kernel 4.13.12-300.fc17.x86_64]
Ryzen 5 1600
R9 270x [X.Org AMD Pitcairn/ 3.0 Mesa 17.2.4]
Running under Wayland display server

I was getting the following error: "Save Failed - Encoding 437 data could not be found. Make sure you have the correct international codeset assembly installed and enabled".

**Comment by mklingen** [comment] 2017-11-16 18:10
Thank you, what is the locale of your machine? EN-US or something else?

**Comment by mklingen** [comment] 2017-11-16 18:21
Seems related to one of our libraries not getting internationalized correctly, likely the ZIP library (which was previously disabled on linux) 

From Xamarin:
>System.NotSupportedException: No data is available for encoding 437
When including 3rd party libraries in your Xamarin.iOS app, you might get an error in the form "System.NotSupportedException: No data is available for encoding 437" when trying to compile and run the app. For example, libraries, such as Ionic.Zip.ZipFile, may throw this exception during operation.

This can be solved by opening the options for the Xamarin.iOS project, going to iOS Build > Internationalization and checking the West internationalization.

**Comment by mklingen** [comment] 2017-11-16 18:24
Hey, if you were on ubuntu you could probably get the internationalization installed on your machine using:

> sudo apt-get install libmono-i18n-west2.0-cil libmono-i18n-west4.0-cil

Not sure how it can be installed on Fedora. If that works we can probably package that with the game.

**Comment by koenigjaeger** [comment] 2017-11-16 18:40
Locale is EN-US. It appears that fedora doesn't provide the packages you listed. 
`dnf search libmono-i18n-west2.0-cil libmono-i18n-west4.0-cil` 
`dnf provides libmono-i18n-west2.0-cil libmono-i18n-west4.0-cil`
both showed nothing.

On a side note would you consider packaging it as a flatpak? In order to solve the dependency issues across multiple linux distros?

**Comment by mklingen** [comment] 2017-11-17 02:06
okay, same error as this one https://github.com/KSP-CKAN/CKAN/issues/367 caused by our use of SharpZipLib. Either we find a way to package mono il8n-west encoding or we turn off compression for save files in linux.

**Comment by JohnRedSnow** [comment] 2017-11-17 18:08
Hello,
I'm having the same issue not being able to save, but I'm running the game in a MacBook Pro.
I had this issue with previous OSX Sierra (can't recall the build), and am having the same issue with OSX High Sierra (-v 10.13.1)

Not sure if you rather have this posted as a different issue, or as it's the same error it should be here.

Regards

**Comment by mklingen** [comment] 2017-11-18 01:33
Okay. Problem likely occurs on all linux and mac builds. Will revert to uncompressed saves this weekend to restore saving/loading for non windows users.

**Comment by koenigjaeger** [comment] 2017-11-18 02:44
Okay, thank you. Looking to play the game soon.

**Comment by mklingen** [comment] 2017-11-18 19:27
Just confirmed this problem exists on Ubuntu and could be solved on that platform by apt-get installing "mono-complete" package. That means we're probably just missing some of the libraries for mono. Will locate them and package them with the game distribution.

**Comment by mklingen** [comment] 2017-11-18 22:58
okay, I have verified that at least on ubuntu this is fixed now and I will have a build out Sunday night. Of course, saves are much larger (~13 MB instead of ~500kb) without compression but at least they work.

**Closed** 2017-11-19 18:57 UTC
Labels: Bug, Cross-Platform, Saving/Loading
