### ISSUE TITLE
Add cyrillic, etc. font support

### ISSUE THREAD

**Issue by Dimonasdf** [CompletelyFairGames/dwarfcorp#415] opened 2017-10-19 15:09 UTC
For localization purposes, you know :)

**Comment by mklingen** [comment] 2017-10-19 16:55
Probably not happening soon, since we pixel all our fonts by hand, but it's a good idea.

**Comment by Dimonasdf** [comment] 2017-10-19 19:41
What about some temporary placeholders?
Honestly, I tried to do it myself, but failed entirely. The biggest problem to me was the fact, that your .yaml files are empty. I guess, this is probably the result of some "default" settings of your development software, where it already knows, that a certain pattern will be used in .png font file and doesn't bother describing it again. I tried using similar .xnb packages with built-in cyrillic support from Terraria and Stardew Valley, but the game just decided to crash and not accept them. But, at the moment of my endeavours, DwarfCorp also happened to have the "I don't want to load your safe files"-problem, so I just decided that I'm asking for too much and let it rest)
So, if you could just extend .png tables (even leaving them empty), and generate .yaml files, containing your font data and aproximate sizes of additional characters, that would be sweet, since the interested people would be able to, maybe, draw some letters and fiddle around with translations and stuff.
I'm not really proficient with programming or developing, of anything, I just spent the day googling and looking if this or that works, so if I happen to be completely wrong about the whole workflow on this issue, just tell me "You don't know, what you're talking about", and I'll leave it.

**Comment by mklingen** [comment] 2017-10-19 19:44
We do not use the XNA sprite font system. We wrote our own system that directly reads the images and interprets the fonts from those images. We could potentially add more symbols to the fonts, or hack together a port from the XNA sprite font system, but it's quite low on our list of things to do.

**Comment by Dimonasdf** [comment] 2017-10-19 19:48
Yeah, I understand) Well, good luck and have fun developing the game) I really like the style, it definitely stands out among other games of the genre.

**Comment by mklingen** [comment] 2017-10-19 19:49
the workflow would look something like creating an image like this:

https://raw.githubusercontent.com/CompletelyFairGames/dwarfcorp/master/DwarfCorp/DwarfCorpContent/newgui/font-10px.bmp

But with the characters needed for that language, or possibly expanding the individual font images with more characters.

For the rest of the localization we would then need to rewrite all of our text and put it into localized data files rather than raw, and switch on a country code to determine which assets to use. DwarfCorp does not have any mechanism to do this currently.

**Comment by Blecki** [comment] 2017-10-19 20:14
Honestly it would be easier to write something to build meshes using sprite font. The point of our system is to generate a mesh that can be cached so the GUI doesn't have to redraw it every frame, something that sprite batch does not support.

**Comment by com1clyf3** [comment] 2018-04-26 02:46
Closing for regression, but localization in general and whether we can do it will definitely be noted on the design prospectus.

**Closed by com1clyf3** 2018-04-26 02:46 UTC
Labels: Design (devs), GUI, Localization / Text
