### ISSUE TITLE
Art: Dwarf art warps when turning back from swimming to map limit

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#610] opened 2018-03-28 21:49 UTC
When dwarves are commanded to map limit, after they reach the limit, when they turn around, their art warps for a second.

1. Command dwarves to swim to map limit.
2. Zoom in 
3. After dwarves reach map limit and turn around, observe the dwarf art warps for a second

Vid: https://drive.google.com/open?id=1GM4cpHtPu7VIjFKC8htYYYpeEpmwP-_R

**Comment by Blecki** [comment] 2018-03-30 00:40
This is because the composite frame is one update behind the dwarf. This is the same reason dwarves flicker when the game first starts.

**Comment by com1clyf3** [comment] 2018-03-31 03:39
So, not fixable?

**Comment by mklingen** [comment] 2018-03-31 20:10
it's fixable. I've also noticed the animations get messed up any time the dwarf enters or leaves water. I think this is a symptom of a more general bug in the animation system that we haven't tracked down yet.

**Comment by Blecki** [comment] 2018-03-31 20:47
I'm still investigating a fix. I have a good idea of what the issue is.

**Comment by mklingen** [comment] 2018-04-16 16:32
Fixed in master.

**Closed by mklingen** 2018-04-16 16:32 UTC
Labels: Art
