### ISSUE TITLE
Minimap angle does not match with Camera angle using overhead views.

### ISSUE THREAD

**Issue by Solsund** [CompletelyFairGames/dwarfcorp#103] opened 2017-02-22 06:51 UTC
The closer you get to an overhead view on the main view the more skewed the Minimap angle gets, normally ending up 90 degrees off.

![image](https://cloud.githubusercontent.com/assets/6342605/23200223/cdc3d272-f898-11e6-9e00-d98a939ccc02.png)

**Comment by mklingen** [comment] 2017-02-23 15:08
This is caused by an arbitrary offset added to the camera position in the minimap. Instead the view matrix should be taken from the main game camera.

**Comment by mklingen** [comment] 2017-02-25 16:37
Fixed in my branch.

**Closed** 2017-02-25 21:26 UTC
Labels: bug
