### ISSUE TITLE
Treasury built, but not functional

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#313] opened 2017-10-02 13:39 UTC
Just what it sounds like.
I built a treasury, but it wasn't being used even after I destroyed the other.
The tiles on the floor even changed to show that the treasury had been built (my craftdwarf went and did his loading bar to build it).
But it just wasn't being used.
Removed the treasury.
Replaced it.
Works, now.

Possibly related to #275.

**Comment by mklingen** [comment] 2017-10-02 13:53
Okay, definitely sounds like its caused by #257 , but I've been unable to reproduce that. It sounds like a common bug so maybe if I play long enough I will encounter it.

**Comment by Orangicus** [comment] 2017-10-02 15:25
I built it on the same spot and it worked fine; it just didn't work properly the first time.

**Comment by kbauer** [comment] 2017-10-02 21:05
I am observing the same behavior. In my current save-game my treasuries are being ignored except for the treasury from the initial spawn. So far I have built two. 

Restarting the game and loading the save didn't help.

Build 17.10.01, Windows 10 Home (64 bit); German Locale.

I attach the save file for reference.
[King Lirnem's County_92.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1350394/King.Lirnem.s.County_92.zip)

**Comment by Orangicus** [comment] 2017-10-03 04:14
Try building it twice, if you would, over the same spot.

**Comment by kbauer** [comment] 2017-10-03 18:45
Building it a second time worked.

I also noticed that the disfunctional treasuries were not removable with build → zones → hold-right-mouse-button as they should be. Apparently they were not being recognized as zone of any kind?

**Comment by Orangicus** [comment] 2017-10-04 03:02
Did you happen to change the size/shape of the treasury while it was being built (craftdwarf with the progress bar up)?

**Comment by mklingen** [comment] 2017-10-04 23:03
@kbauer I just loaded your save, this was actually extremely useful data for me, because it seems to reproduce the "dwarves are not selectable" bug I've been trying to track down. The treasuries are also definitely not valid, and I've been trying to reproduce that bug, but with no luck. However, now that I have a hold on the "dwarves are not selectable #314" bug I should at least be able to fix that!

**Comment by Orangicus** [comment] 2017-10-05 04:07
GOOD. That's been killing every single one of my games as soon as I build more treasury/stockpile/port.

**Comment by mklingen** [comment] 2017-10-05 11:20
selection issue fixed by this commit https://github.com/CompletelyFairGames/dwarfcorp/commit/207727da0ba4da1d2d8bdb3fd009549c53fbd2f8 . still trying to reproduce treasury issue.

**Comment by BombBloke** [comment] 2017-10-05 13:18
I realise this won't sound helpful (and that I've already mentioned this), but the zoning issue most commonly occurs for me when I'm not trying to produce it. My suspicions are that it's related to the existence of other orders existing in the builder's queue (construction orders seem to supersede anything else he was doing), or demand for the zone (eg a treasury may be more likely to fail if dwarves (the builder maybe?) have gold they can't dump anywhere else), or some combination thereof; as when the issue *happens* there's a good chance it'll happen *multiple times in a row*. That makes me lean away from "total luck".

I also feel it's worth re-iterating that the issue does not solely affect treasury zones. It's more generic than that.

**Comment by mklingen** [comment] 2017-10-07 14:36
been trying to reproduce issue and have been unable to so far. I will analyze the code to see how this could even be possible.

**Comment by mklingen** [comment] 2017-10-21 21:29
Fixed by this commit https://github.com/CompletelyFairGames/dwarfcorp/commit/2754228b8ed29f006207f7a14765fbdd6a395669

It was actually caused by dwarf mining. If a dwarf mined a block while a room was being built, then the room would get a check that said "this room is empty! delete it!" but the room is not built yet, so it's empty, and hence gets deleted.

**Closed by mklingen** 2017-10-21 21:29 UTC
Labels: AI, Bug
