### ISSUE TITLE
Building blocks often causes game to crash due to nullable not being set.

### ISSUE THREAD

**Issue by MasterRainwater** [CompletelyFairGames/dwarfcorp#534] opened 2018-01-25 05:12 UTC
https://imgur.com/9wKYmxU via @imgur

**Comment by mklingen** [comment] 2018-02-03 21:55
Thank you for reporting this. It's actually a a very common crash (happened to a few hundred people while I was on vacation). caused by https://github.com/CompletelyFairGames/dwarfcorp/commit/e4a468de3d5a2e72d2f6bebb6d5e64130054174a

Fixed by recent commit. Fix will be in the next build.

**Closed** 2018-02-05 16:54 UTC
Labels: Bug, Crash
