### ISSUE TITLE
Crash on loading game

### ISSUE THREAD

**Issue by megamanzteam** [CompletelyFairGames/dwarfcorp#411] opened 2017-10-17 19:36 UTC
I try to load my game and it crashes to desktop. I looked through the log file and don't see any obvious errors. Also no crash report was generated at AppData/Roaming/DwarfCorp/Logging. In fact that location doesn't exist.
[log.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/1392365/log.txt)
[DwarfCorp.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1392369/DwarfCorp.zip)

I have attached the log and zipped everything from the save location to help you.

**Comment by mklingen** [comment] 2017-10-17 20:40
Which version of the game are you running, on which platform? It should be showing you an error message on load.

**Comment by megamanzteam** [comment] 2017-10-18 22:23
I think I am on the latest build 10.17.15 on Steam. I don't get any error, or if I do it is to quick for me to see. It does seem to happen just shortly after loading entities. Windows says there was an issue and is looking for a solution is the closest to an error I can get.

**Comment by mklingen** [comment] 2017-10-18 22:37
hmm, I'm sorry about that. Hopefully our crash reporting system caught this error.  The game is supposed to be showing an error message if there's something that would cause a crash there, but it looks like it never gets to that point in your case. Does this happen all the time with any save, or just one particular save?

**Comment by megamanzteam** [comment] 2017-10-18 22:41
For now I have the only one save. I could try starting a new game if needed, to see if I can reproduce the problem.

**Comment by mklingen** [comment] 2017-10-18 23:06
It's okay. I managed to get your save file (almost) loaded, but we've made a lot of changes since sunday so its hard to say what the root issue could have been.

**Comment by megamanzteam** [comment] 2017-10-19 02:29
OK, starting a new game works. However when I go to load it again, the new game also failed to load. I have attached a zip of my saves/world/log
[DwarfCorp.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1396892/DwarfCorp.zip)

**Comment by megamanzteam** [comment] 2017-10-21 18:52
So far playing with debug world has not crashed or errored when loading that file.

**Comment by mklingen** [comment] 2017-10-21 22:20
Going to close this since there isn't anything I can do to reproduce it. May have fixed the underlying issue already.

**Closed by mklingen** 2017-10-21 22:20 UTC
Labels: Bug, Crash, Saving/Loading
