### ISSUE TITLE
Camera can not move when pointing straight up/down.

### ISSUE THREAD

**Issue by Solsund** [CompletelyFairGames/dwarfcorp#48] opened 2017-01-20 20:59 UTC
Camera movement seems to be based on rotational angle even when not in RotationalMode.  This causes the math to fail when we are pointing straight up or down.

Right/Left movement fails completely and Forward/Backward fails when not holding Shift.

**Comment by mklingen** [comment] 2017-01-28 01:27
Caused by incorrect up and forward vector when camera pointing exactly downward. Will fix.

**Comment by mklingen** [comment] 2017-01-28 01:32
Fixed by PR.

**Closed by mklingen** 2017-01-28 01:32 UTC
Labels: bug
