### ISSUE TITLE
Creatures chase each other in water indefinitely

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#644] opened 2018-04-15 20:29 UTC
Spawn some creatures which naturally hate each other (such as snakes and goblins) in a pool of water. Watch them chase each other for hours, since neither can attack in water.

**Comment by mklingen** [comment] 2018-04-16 02:10
This was caused by fixing #606, which was fixed in a too-general way. This caused all planning within water to fail. Also it is caused by the fact that some creatures (like scorpions) just can't swim.

Fixed in master.

**Closed by mklingen** 2018-04-16 02:10 UTC
Labels: AI
