### ISSUE TITLE
Beds unused

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#343] opened 2017-10-07 18:40 UTC
Despite having accessible beds, most of the time dwarfs all of a sudden fall asleep on the floor during work.
![dwarfcorp_beds_unused](https://user-images.githubusercontent.com/3519989/31310845-a5e4d9c6-ab9f-11e7-9302-b6b2e60215cf.PNG)

**Comment by mklingen** [comment] 2017-10-07 18:56
I can't reproduce this. What were the steps you might have taken?

**Comment by Orangicus** [comment] 2017-10-07 19:08
Based on the image, might be related to beds being inaccessible due to being too close together.

**Comment by Aikhjarto** [comment] 2017-10-07 19:09
@Orangicus early in the game, I had 5 of these beds that close together. The dwarfs slept there.

**Comment by mklingen** [comment] 2017-10-07 19:11
probably a save/load bug... do the dwarves sleep in *new* beds?

**Comment by mklingen** [comment] 2017-10-07 19:11
being close together should not be a problem.

**Comment by mklingen** [comment] 2017-10-08 15:39
fixed by https://github.com/CompletelyFairGames/dwarfcorp/commit/b7b479f48d57787a10223dc9cedddfd331f307bb will be in the patch today.

**Closed by mklingen** 2017-10-08 15:39 UTC
Labels: AI, bug
