### ISSUE TITLE
Game Slows down

### ISSUE THREAD

**Issue by lemonrev** [CompletelyFairGames/dwarfcorp#377] opened 2017-10-09 08:27 UTC
Mid game once you have built quite a bit and dug some holes i had only 6 dwarfs and found the game still slowing down then it speeds up, If there was some type of graph i could pull up while playing the game that you could make available i could actually show the game being slow.

but as i say it speeds right up again.

**Comment by mklingen** [comment] 2017-10-09 15:41
Can you press F10? That will display some debug information, and if you take a screenshot that will really help.

**Comment by BombBloke** [comment] 2017-10-10 01:00
I've been putting this down to the discovery of new areas: fog of war seems to be cleared from all tiles your dwarves can reach (as opposed to all tiles they have an actual line of sight on), so opening up a new cave system can potentially reveal a whole lot of blocks all in one go.

Either that or the path system.

**Comment by mklingen** [comment] 2017-10-13 13:03
yeah I'm guessing that revealing caves slows the game down for a while as all the creatures wake up simultaneously.

**Comment by Searthh** [comment] 2017-10-16 21:59
_DwarfCorp Version: 8f281af (XNA version) / OS: Windows 10 Home 1703 / 64 bit / 8 GB RAM / Interl i5 7200U @2.50 GHz 2.70 GHz_

I can confirm that serious slowdown happens when discovering caves. I get about 2 FPS unpaused, and 25 FPS paused playing on a medium map while uncovering caves.

![image](https://user-images.githubusercontent.com/32852691/31637154-a9e7b41e-b2cd-11e7-88bc-11ff8fc1ca9f.png)

**Comment by mklingen** [comment] 2017-10-17 12:29
Okay, we are thinking about changing the way caves get revealed so that smaller portions of them get revealed at once.

**Comment by mklingen** [comment] 2017-10-19 17:00
Related to #301

**Comment by com1clyf3** [comment] 2018-04-25 18:15
Could still be a contributing factor. Closing for regresssion but linking to #651

**Closed by com1clyf3** 2018-04-25 18:15 UTC
Labels: Design (devs), Performance
