### ISSUE TITLE
Dwarves Starvation glitch

### ISSUE THREAD

**Issue by azbutterbean10** [CompletelyFairGames/dwarfcorp#433] opened 2017-10-24 04:41 UTC
Hi guys,

I had an issue today while playing your game after roughly three hours play time. All at once, it seemed that my dwarves stopped moving and a few of them were starving, and the task they had was trying to resolve hunger. None of them could move, even dwarves who were not starving yet. I had a mining dwarf crafting some food, but am unsure if they were able to finish before or after this issue started, when i checked the backpack on that dwarf, it only had 1 food item on it even though I ordered it to craft 10. This dwarf also did not attempt to eat the food item even though it was starving. 

For some reason I also experienced extreme performance drop once they all began to starve and take damage. Tried to reload my save and when I did, the dwarves initially started to run about, but once they reached that initial move destination, they all stopped moving again and continued to starve. 

Hope this helps, did not see another post about starving dwarves.

**Comment by azbutterbean10** [comment] 2017-10-24 04:43
Thought it may be similar to #365

**Comment by azbutterbean10** [comment] 2017-10-24 04:46
this is addressed in #241

**Comment by mklingen** [comment] 2017-10-24 13:13
Okay, several people have mentioned this. It will be hard for me to reproduce as it only seems to happen after playing the game for a long period of time. I have added a test button in god mode to make dwarves starve, but was unable to reproduce the bug that way.

**Comment by CaptDeathCap** [comment] 2017-10-25 15:33
I've had this issue more and more, basically ends every single one of my games, now. Sometimes it happens in no time flat. Like...twenty minutes after I started with a new colony.

**Comment by mklingen** [comment] 2017-10-25 16:52
Okay, will try to reproduce. Likely some kind of pathfinding bug. Crash is this issue https://github.com/CompletelyFairGames/dwarfcorp/issues/421

**Comment by mklingen** [comment] 2017-10-28 12:11
Fixed in the recent build using my suggestion. Still not desirable but much better.

**Closed by mklingen** 2017-10-28 12:11 UTC
Labels: AI, Bug, duplicate
