### ISSUE TITLE
Reproducible crash in save-file, for unknown reason.

### ISSUE THREAD

**Issue by kbauer** [CompletelyFairGames/dwarfcorp#336] opened 2017-10-07 10:10 UTC
In the attached save [1], the game crashes after a few seconds without a user-visible error message.

The only observed condition, is that it happens shortly after the dwarves finish excavating the mine on the hill. 

![excav](https://user-images.githubusercontent.com/7498468/31306846-39f04dbe-ab58-11e7-81aa-13d88d2ba1b2.png)

Other than that, I couldn't observe a specific trigger. 
- After cancelling the pickup-order for the destroyed stockpile, the crash still occurs.
- Giving them something else todo, also doesn't prevent a crash.

## Attachments

[1] [Crateia_273 - Crash when picking up drops - 17.10.01, bugfix.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1364431/Crateia_273.-.Crash.when.picking.up.drops.-.17.10.01.bugfix.zip), created in the current steam release ("bugfix" after 17.10.01).

**Comment by mklingen** [comment] 2017-10-07 14:04
reproduced crash. Seems to be caused by a trade envoy from the Motherland arriving, but there is no balloon port for them to go to. Will fix with a warning to the player that they cannot trade without a balloon port.

**Comment by mklingen** [comment] 2017-10-07 14:07
also, in this save your company has $0.00, and no treasuries. The dwarves are trying and failing to get paid, and are just standing around. Will add a check to force dwarves to tantrum instead of standing around when they can't get paid.

**Comment by mklingen** [comment] 2017-10-07 14:18
Fixed by https://github.com/CompletelyFairGames/dwarfcorp/commit/8c6154a3cda5d83976ae0f6dcb88ada5b28166af will be in the next build.

**Closed by mklingen** 2017-10-07 14:18 UTC
