### ISSUE TITLE
AI: All birds are flying on the ground

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#775] opened 2018-07-02 21:38 UTC
![image](https://user-images.githubusercontent.com/6562812/42187519-5e395f28-7e1e-11e8-85ed-18b722827b7f.png)

Birds are flying normally to start with. At some point that began to stay grounded while flying.

[Land of Flamebattler_292_131750408454833334.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2156873/Land.of.Flamebattler_292_131750408454833334.zip)

[Land of Flamebattler.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2156876/Land.of.Flamebattler.zip)

236e5063

**Comment by mklingen** [comment] 2018-07-21 18:47
This was caused by a couple of things. 1) bird gravity compensation was not high enough. Over time they would tend to fly lower and lower. 2) there was a feedback loop whereby if the bird couldn't find a perch (for example if it was over water), it's state would never get reset, and due to (1) it would be unable to fly higher.

fixed in master.

**Closed by mklingen** 2018-07-21 18:47 UTC
Labels: AI
