### ISSUE TITLE
Zones: baloon ports not being used correctly

### ISSUE THREAD

**Issue by djdunn** [CompletelyFairGames/dwarfcorp#522] opened 2018-01-10 01:05 UTC
when i build a new balloon port, then destroy the starting one, the dwarves won't store things in the new balloon port, also if i try to hire a dwarf, they will instantly die as they are spawned, (no bodies, but ge the such and such has died message) 
I get this issue on both linux and windows versions.

**Comment by mklingen** [comment] 2018-01-16 11:33
okay will try to reproduce.

**Comment by mklingen** [comment] 2018-01-16 11:40
hmm, I'm unable to reproduce this. Where did you build the balloon port? How bit was it?

**Comment by mklingen** [comment] 2018-04-10 15:42
I think this may be another manifestation of #624 . It seems there are still some circumstances were zones fail to get built properly.

**Comment by com1clyf3** [comment] 2018-04-26 21:55
@Sydonia  Could you send us that save, if you still have it? Probably too long ago at this point, but same goes for @djdunn if you've got it.

Sounds like this is possibly more than one bug.

**Comment by Sydonia** [comment] 2018-04-26 23:44
Hey guys I have several saves still with this bug (6 total) I am more than willing to upload them if you can tell me where I can find them. I've looked and they are well hidden on my machine.

**Comment by com1clyf3** [comment] 2018-04-27 01:53
Hey @Sydonia  I can help you with that, sure. What OS are you on?

**Comment by Sydonia** [comment] 2018-04-27 18:13
Sorry about the delay. I am on Windows 7. I know it's old but it runs
absolutely everything you throw at it.

**Comment by com1clyf3** [comment] 2018-04-27 19:13
@Sydonia  So everything should be in your APPDATA file. To reach it follow this path: My PC > Users > Your Window's Username > Appdata. If you're not seeing the Appdata folder, it's possible your PC is hiding sensitive files. To make them appear follow this:  https://www.howtogeek.com/howto/windows-vista/show-hidden-files-and-folders-in-windows-vista/

In the Appdata folder you should see only two or three folders. Go to Open Roaming > Dwarfcorp

Now you should see all the good stuff. Your saves should be in the save folder. We'll also need any corresponding world files as well. Don't change any of the file names. Throw them in  a .zip or two (that's what GitIssues prefers). Then send them over, and we'll take a look.

**Comment by Sydonia** [comment] 2018-04-27 21:57
[Saves.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1956785/Saves.zip)

There you go. There are 3 save files per "game" all seem to have the same issue. I have no idea why I didn't check the roaming folder.

Hope these help and if there is anything else I can do feel free to ask.

**Comment by Sydonia** [comment] 2018-04-28 13:39
I apologize I thought that Sea of Feather was also bugged. It is not the
other two are though. My mistake.

**Comment by djdunn** [comment] 2018-05-06 02:43
sorry no saves from back then.

**Comment by com1clyf3** [comment] 2018-07-20 19:34
Closing for regression. Prbably will be covered by #798 anyways.

**Closed by com1clyf3** 2018-07-20 19:34 UTC
Labels: AI, Build
