### ISSUE TITLE
Crash on "Continue": system.FormatException

### ISSUE THREAD

**Issue by kbauer** [CompletelyFairGames/dwarfcorp#277] opened 2017-09-28 18:43 UTC
When pressing "Continue" in the "MAIN MENU", a `system.FormatException` occurs.

### Save-State and settings
[AppData_Roaming_DwarfCorp.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1341938/AppData_Roaming_DwarfCorp.zip)

### Exception Screenshot

The log.txt doesn't seem to be any help on this (doesn't contain the backtrace), so I attach a screenshot.

![Screenshot of Exception](https://user-images.githubusercontent.com/7498468/30984114-bba0160a-a48c-11e7-9ff2-6054b342b7b2.png)

A possible hint may be modification time. I'm pretty sure I stopped playing later than 23:20, though it isn't sure. The `screenshot.png` however, *definitely* doesn't show the final state of the settlement.

**Comment by mklingen** [comment] 2017-09-28 18:48
Duplicate of #243

**Comment by mklingen** [comment] 2017-09-28 23:46
possibly fixed by this https://github.com/CompletelyFairGames/dwarfcorp/commit/d65ec59e9165a2eb577ef0cab00d770b52e9a4f1

**Closed** 2017-09-29 00:31 UTC
Labels: duplicate, Saving/Loading
