### ISSUE TITLE
Crash:  Universal Selector causes crash - System.NullReferenceException: Object reference not set to an instance of an object. -

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#793] opened 2018-07-09 21:00 UTC
Crash occurred while using wrangle. No clear reason repro. 

[201807091637286715_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2177975/201807091637286715_Crashlog.txt)

[Scintillating Hills_720_131756409724367454.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2177980/Scintillating.Hills_720_131756409724367454.zip)
[Scintillating Hills.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2177981/Scintillating.Hills.zip)

27b0c862

**Comment by com1clyf3** [comment] 2018-07-09 21:11
[201807091708332800_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2178019/201807091708332800_Crashlog.txt)

Got it to happen again. After selecting a frog to wrangle and then using the universal selector to highlight a bunch of enemies. I'll try and verify the repro now.

**Comment by com1clyf3** [comment] 2018-07-09 21:15
Repro found. 

1. Load attached save.
2. Use universal selector to highlight a bunch of entities around the balloonport.
3. Crash to desktop.

Debug Output:`` C:\Users\kingofarabi1\AppData\Roaming\DwarfCorp\settings.json
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\Microsoft.Xna.Framework.Xact\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.Xact.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Xna.Framework.GamerServices\v4.0_4.0.0.0__842cf8be1de50553\Microsoft.Xna.Framework.GamerServices.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\bin\x86\Release\LibNoise.dll'. Symbols loaded.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\bin\x86\Release\ICSharpCode.SharpZipLib.dll'. Module was built without symbols.
The thread 0x13a0 has exited with code 0 (0x0).
Exception thrown: 'System.NullReferenceException' in DwarfCorp.exe
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Cannot find or open the PDB file.
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'DwarfCorp.exe' (CLR v4.0.30319: DwarfCorp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Dynamic\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Dynamic.dll'. Cannot find or open the PDB file.
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'System.NullReferenceException' in DwarfCorp.exe
The thread 0x2d80 has exited with code 0 (0x0).
The thread 0x1ddc has exited with code 0 (0x0).
The thread 0x3218 has exited with code 0 (0x0).
The thread 0x9a4 has exited with code 0 (0x0).
The thread 0x284c has exited with code 0 (0x0).
``

**Comment by mklingen** [comment] 2018-07-21 23:36
duplicate of another bug I fixed today.

**Closed by mklingen** 2018-07-21 23:36 UTC
Labels: A Bug, Crash, GUI, wrangle
