### ISSUE TITLE
Items from destroyed zones cannot be picked up; Not reproducible in fresh saves.

### ISSUE THREAD

**Issue by kbauer** [CompletelyFairGames/dwarfcorp#335] opened 2017-10-06 19:08 UTC
## Normal behavior

- Destroy a stockpile / baloon port / treasury.
- Command dwards to pick the dropped items up.
- They will be moved to available free space.

## Occasional behavior

- Destroy ... 
- The dropped items cannot be marked for pick-up and the dwarves don't do anything by themselves.

## Details

**Not reproducible on fresh saves!** Creating several new games, I was never able to reproduce the issue (e.g. attachment [2]).

For new games, save/quit/reload doesn't trigger the issue either. 

It did however occur several times over the last patches for me. I uploaded an example save-game (attachment [1]) where destroying the stockpiles on top of the hill yields broken drops every time I try. 

In attachment [1], the issue occurs for *all* stockpiles / treasuries / balloon ports, including nearly empty ones, i.e. it doesn't seem to be related to the large number of dropped items from full stockpile zones.

Affected use-case: Re-locating the center of the settlement.

## Attachments (Savegames)
[1] [Picking up items, gold fails.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1363606/Picking.up.items.gold.fails.zip)
[2] [Picking up items, gold succeeds.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1363607/Picking.up.items.gold.succeeds.zip)

**Comment by mklingen** [comment] 2017-10-06 19:58
most likely duplicate of #314 , which was recently fixed and will be in the next build.

**Comment by mklingen** [comment] 2017-10-06 19:59
when you mouse over the items, what does it say in the info panel? (bottom left)

**Comment by kbauer** [comment] 2017-10-06 20:11
For affected saves, 
- nothing at all appears in the info panel
- dwarfes are only selectable through the tool-bar, but not by selection-rectangle or clicking

For unaffected saves, 
- the item name shows up in the info panel
- dwarfs are selectable by click, selection-rectangle, and tool-bar.

Which probably verifies the duplicate-of- #314 -status.

**Comment by mklingen** [comment] 2017-10-07 14:18
Okay, duplicate of #314. Fixed and will be in the next build.

**Closed by mklingen** 2017-10-07 14:18 UTC
Labels: bug
