### ISSUE TITLE
GUI: Collected built objects are not counted as individual resources

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#784] opened 2018-07-05 18:35 UTC
The upper resource display is showing all crafted objects in a single slot, with the art changing somewhat randomly, versus showing each resource in its own slot.

![image](https://user-images.githubusercontent.com/6562812/42341188-366b564c-8060-11e8-8c8b-c560f3b5e280.png)

The upper menu reads 24 forges collected after sending dwarves to collect all the items from a craft spawn.

1. Craft spawn
2. Destroy all.
3. Gather all.
4. Observe upper resource menu as it counts many different kinds of built objects as one resource with changing art.

62c295a9

**Comment by mklingen** [comment] 2018-07-07 13:39
Not a bug but by design. Objects that share the same tags are merged together to save space on the GUI.

**Closed by mklingen** 2018-07-07 13:39 UTC
Labels: Build, GUI

**Comment by com1clyf3** [comment] 2018-07-09 18:42
Hm. Not a great design, but it'll do. If player decides to become a trader in just built objects, they won't have a good way to know what they have until a trade screen appears. Could we maybe add a separate count for built objects. Like clicking on the built objects icon in the overhead icon will open a small menu printing what they've got? They can drag and drop the menu/leave it on screen if they want the counter, but otherwise X out of it?

**Comment by Blecki** [comment] 2018-07-09 18:49
Mousing over shows this already.

**Comment by com1clyf3** [comment] 2018-07-09 18:57
Oh cool. That works then. Haven't tried the updated build yet.
