### ISSUE TITLE
Camera can become stuck in the sky

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#282] opened 2017-09-29 03:46 UTC
<s>Not 100% sure how to replicate this, but this is what evidence suggests. Will edit when I have more info/ experience with the bug.</s>

<s>If you select a dwarf and "follow" them without initiating manual control, then exit out of their profile by selecting, for instance terrain instead, your WASD control scheme will be 'locked.' It won't allow you to move more than the tiniest bit in any direction. I assume this is because you're stuck in 'manual control' mode? Selecting any dwarf and exercising manual control for any period of time solves this issue when you exit the dwarf's profile.</s>

Persists with saves.

So I got stuck in the sky because I zoomed out a tad too much, and doing so prevents you from moving until you zoom way back in.

**Comment by mklingen** [comment] 2017-09-30 18:12
duplicate of #280

**Closed by mklingen** 2017-09-30 18:12 UTC
Labels: bug, User-Experience
