### ISSUE TITLE
Loading not Possible (Ubuntu 17.10) 

### ISSUE THREAD

**Issue by Escaflow** [CompletelyFairGames/dwarfcorp#520] opened 2018-01-06 18:55 UTC
Wanted to try out a few Cases where it happens but... it happens every time.

Fresh Start Save-Load (error in Pic/Save in .zip).

Did a strace to look for opened files:

strace -e trace=open ./DwarfCorpFNA.bin.x86_64

```
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
open("/dev/shm/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 3
open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 3
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 3
open("/usr/share/locale/en_GB/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_GB/LC_MESSAGES/libc.mo", O_RDONLY) = 3
open("/usr/share/locale-langpack/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 3
open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 3
process 1684: arguments to dbus_type_is_basic() were incorrect, assertion "dbus_type_is_valid (typecode) || typecode == DBUS_TYPE_INVALID" failed in file ../../../dbus/dbus-signature.c line 322.
This is normally a bug in some application using the D-Bus library.
type unknown isn't supported yet in dbus_message_append_args_valist
open("/dev/dri", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 9
open("/dev/dri", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 9
open("/dev/dri", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 9
open("/dev/dri", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 10
open("/dev/dri", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 10
open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 11
open("/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 11
open("/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache", O_RDONLY) = 11
open("/sys/bus", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 12
open("/sys/class", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 12
open("/sys/class/sound/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 13
open("/sys/class/input/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 13
open("/sys/bus", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 12
open("/sys/class", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 12
open("/sys/class/sound/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 13
open("/sys/class/input/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 13
Controller 0: XInput Controller
open("/etc/pulse/client.conf.d", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/dev/shm/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 16
open("/usr/share/locale/en_GB/LC_MESSAGES/pulseaudio.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/pulseaudio.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_GB/LC_MESSAGES/pulseaudio.mo", O_RDONLY) = 17
open("/usr/share/locale-langpack/en/LC_MESSAGES/pulseaudio.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/etc/pulse/client.conf.d", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/dev/shm/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 16
open("/etc/pulse/client.conf.d", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/dev/shm/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 21
open("/etc/pulse/client.conf.d", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/dev/shm/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 21
IGLDevice: OpenGLDevice
OpenGL Device: AMD HAWAII (DRM 2.50.0 / 4.13.0-21-generic, LLVM 5.0.0)
OpenGL Driver: 3.0 Mesa 17.2.4
OpenGL Vendor: X.Org
MojoShader Profile: glsl120
EXT_swap_control_tear unsupported. Fall back to standard VSync.
Loaded settings {
  "TutorialDisabledGlobally": false,
  "ResolutionX": 1920,
  "ResolutionY": 1080,
  "GuiScale": 1,
  "GuiAutoScale": true,
  "ChunkDrawDistance": 115.688126,
  "VertexCullDistance": 1000.0,
  "AntiAliasing": -1,
  "Fullscreen": false,
  "EnableGlow": true,
  "DrawSkyReflected": true,
  "DrawChunksReflected": true,
  "DrawEntityReflected": false,
  "AmbientOcclusion": true,
  "CalculateRamps": true,
  "CameraScrollSpeed": 10.0,
  "CameraZoomSpeed": 0.5,
  "EnableEdgeScroll": true,
  "WorldScale": 4.0,
  "DisplayIntro": true,
  "MasterVolume": 1.0,
  "SoundEffectVolume": 1.0,
  "MusicVolume": 0.2,
  "CursorLightEnabled": true,
  "EntityLighting": true,
  "SelfIlluminationEnabled": true,
  "ParticlePhysics": true,
  "GrassMotes": true,
  "NumMotes": 2048,
  "InvertZoom": false,
  "ChunkGenerateDistance": 80.0,
  "ChunkRebuildTime": 0.1,
  "ChunkUnloadDistance": 250.0,
  "DrawDebugData": false,
  "VisibilityUpdateTime": 0.05,
  "ChunkGenerateTime": 0.5,
  "FogofWar": true,
  "UseDynamicShadows": false,
  "UseLightmaps": false,
  "DrawPaths": false,
  "AutoSave": true,
  "AutoSaveTimeMinutes": 120.0,
  "SaveLocation": "",
  "VSync": true,
  "AllowReporting": true,
  "ZoomCameraTowardMouse": true,
  "CameraFollowSurface": true
} 
 /home/escaflow/.local/share/DwarfCorp/settings.json
EXT_swap_control_tear unsupported. Fall back to standard VSync.
open("/home/escaflow/.local/share/DwarfCorp/Saves", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 21
open("/home/escaflow/.local/share/DwarfCorp/Saves/Glibland_546", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 21
open("/home/escaflow/.local/share/DwarfCorp/Saves/Glibland_546", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 21
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x18} ---
open("/home/escaflow/.local/share/DwarfCorp/Saves", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 21
open("/home/escaflow/.local/share/DwarfCorp/Saves/Glibland_546", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 21
open("/home/escaflow/.local/share/DwarfCorp/Saves/Glibland_546", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 21
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x18} ---
open("/home/escaflow/.local/share/DwarfCorp/Saves/Glibland_546", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 21
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x18} ---
open("/mnt/Games/steamapps/common/DwarfCorp/Content/Text", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 21
--- SIGPWR {si_signo=SIGPWR, si_code=SI_TKILL, si_pid=1684, si_uid=1000} ---
--- SIGXCPU {si_signo=SIGXCPU, si_code=SI_TKILL, si_pid=1684, si_uid=1000} ---
--- SIGPWR {si_signo=SIGPWR, si_code=SI_TKILL, si_pid=1684, si_uid=1000} ---
--- SIGXCPU {si_signo=SIGXCPU, si_code=SI_TKILL, si_pid=1684, si_uid=1000} ---
--- SIGINT {si_signo=SIGINT, si_code=SI_KERNEL} ---
strace: Process 1684 detached
```

![screenshot from 2018-01-06 19-34-34](https://user-images.githubusercontent.com/25120195/34642787-6f581b90-f319-11e7-8014-05c674797f97.png)
![screenshot from 2018-01-06 19-40-01](https://user-images.githubusercontent.com/25120195/34642788-6f73974e-f319-11e7-9484-a011f3a8d791.png)
[Glibland_546.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1609087/Glibland_546.zip)

**Comment by mklingen** [comment] 2018-01-06 18:58
Oh no, looks like the system is failing to open the directory containing the save. Can I ask what permissions are on that directory?

**Comment by mklingen** [comment] 2018-01-06 19:06
Also, are you able to load worlds? (By going to new game > advanced > Load World)

**Comment by Escaflow** [comment] 2018-01-06 19:12
Sure but its in my home folder so i have access to all:

ls -Rl /home/escaflow/.local/share/DwarfCorp/
```
/home/escaflow/.local/share/DwarfCorp/:
total 211348
-rw-rw-r-- 1 escaflow escaflow       475 Dez 24 15:32 controls.json
-rw-rw-r-- 1 escaflow escaflow 216384946 Jan  6 19:48 log.txt
drwxr-xr-x 3 escaflow escaflow       230 Jan  6 19:47 Saves
-rw-rw-r-- 1 escaflow escaflow      1245 Jan  6 18:49 settings.json
drwxr-xr-x 7 escaflow escaflow       282 Jan  6 19:32 Worlds

/home/escaflow/.local/share/DwarfCorp/Saves:
total 1648
drwxr-xr-x 3 escaflow escaflow       0 Jan  6 19:32 Glibland_546
-rw-rw-r-- 1 escaflow escaflow 1676455 Jan  6 19:43 Glibland_546.zip

/home/escaflow/.local/share/DwarfCorp/Saves/Glibland_546:
total 14708
drwxr-xr-x 2 escaflow escaflow        0 Jan  6 19:32 Chunks
-rw-r--r-- 1 escaflow escaflow      649 Jan  6 19:32 Metadata.meta
-rw-r--r-- 1 escaflow escaflow   816131 Jan  6 19:32 screenshot.png
-rw-r--r-- 1 escaflow escaflow 14213115 Jan  6 19:32 World.save

/home/escaflow/.local/share/DwarfCorp/Worlds:
total 0
drwxrwxr-x 2 escaflow escaflow   0 Jan  6 18:47 Bigia
drwxr-xr-x 2 escaflow escaflow 282 Dez 26 23:12 Combativeland
drwxr-xr-x 2 escaflow escaflow 282 Dez 24 17:27 Flaky Hills
drwxr-xr-x 2 escaflow escaflow   0 Jan  6 19:32 Glibland
drwxr-xr-x 2 escaflow escaflow 282 Dez 24 17:17 Pet Realm

/home/escaflow/.local/share/DwarfCorp/Worlds/Bigia:
total 356
-rw-rw-r-- 1 escaflow escaflow   3172 Jan  6 18:47 meta.txt
-rw-rw-r-- 1 escaflow escaflow 148268 Jan  6 18:48 screenshot.png
-rw-rw-r-- 1 escaflow escaflow 184191 Jan  6 18:47 world.png

/home/escaflow/.local/share/DwarfCorp/Worlds/Combativeland:
total 340
-rw-r--r-- 1 escaflow escaflow   3176 Dez 26 23:12 meta.txt
-rw-r--r-- 1 escaflow escaflow 134454 Dez 27 18:54 screenshot.png
-rw-r--r-- 1 escaflow escaflow 182939 Dez 26 23:12 world.png

/home/escaflow/.local/share/DwarfCorp/Worlds/Flaky Hills:
total 348
-rw-r--r-- 1 escaflow escaflow   3174 Dez 24 17:27 meta.txt
-rw-r--r-- 1 escaflow escaflow 144982 Dez 24 17:27 screenshot.png
-rw-r--r-- 1 escaflow escaflow 180057 Dez 24 17:27 world.png

/home/escaflow/.local/share/DwarfCorp/Worlds/Glibland:
total 332
-rw-r--r-- 1 escaflow escaflow   3182 Jan  6 19:32 meta.txt
-rw-r--r-- 1 escaflow escaflow 138121 Jan  6 19:32 screenshot.png
-rw-r--r-- 1 escaflow escaflow 170761 Jan  6 19:32 world.png

/home/escaflow/.local/share/DwarfCorp/Worlds/Pet Realm:
total 332
-rw-r--r-- 1 escaflow escaflow   3173 Dez 24 17:17 meta.txt
-rw-r--r-- 1 escaflow escaflow 139038 Dez 24 17:17 screenshot.png
-rw-r--r-- 1 escaflow escaflow 169206 Dez 24 17:17 world.png

```
Generate new World, saved it and tried to load instant crash:
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at DwarfCorp.NewOverworldFile+OverworldData.LoadFromTexture (Microsoft.Xna.Framework.Graphics.Texture2D Texture) [0x00000] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
  at DwarfCorp.NewOverworldFile.ReadFile (System.String filePath) [0x0004c] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
  at DwarfCorp.NewOverworldFile..ctor (System.String fileName) [0x00006] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
  at DwarfCorp.GameStates.WorldLoaderState+<>c__DisplayClass0_0.<.ctor>b__4 (System.String path) [0x00000] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
  at DwarfCorp.GameStates.PaginatedChooserState.<OnEnter>b__20_0 (DwarfCorp.Gui.Widget sender, DwarfCorp.Gui.InputEventArgs args) [0x00029] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
  at DwarfCorp.Gui.Root.SafeCall[T] (System.Action`2[T1,T2] Action, DwarfCorp.Gui.Widget Widget, T Args) [0x00003] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
  at DwarfCorp.Gui.Root.CallOnClick (DwarfCorp.Gui.Widget Widget, DwarfCorp.Gui.InputEventArgs Args) [0x00000] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
  at DwarfCorp.Gui.Root.HandleInput (DwarfCorp.Gui.InputEvents Event, DwarfCorp.Gui.InputEventArgs Args) [0x00352] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
  at DwarfCorp.GameStates.PaginatedChooserState.Update (DwarfCorp.DwarfTime gameTime) [0x0001a] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
  at DwarfCorp.GameStates.GameStateManager.Update (DwarfCorp.DwarfTime time) [0x0007a] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
  at DwarfCorp.DwarfGame.Update (Microsoft.Xna.Framework.GameTime time) [0x0002c] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
AL lib: (EE) alc_cleanup: 1 device not closed

```
Same result with a normal save.

**Comment by mklingen** [comment] 2018-01-06 19:13
Interesting, okay. I think it might be the new SDL we included, or perhaps the wrong version of libpng. Will look  around.

**Comment by Escaflow** [comment] 2018-01-06 19:29
Testet the SDL from steam and the one from the repostiory (libSDL2-2.0.so.0.6.0), no Cigar.
Testet the repo libpng (libpng16.so.16.34.0) to, same effect.

**Comment by mklingen** [comment] 2018-01-06 19:51
That's too bad. In any case next release will have some more logging there to figure out precisely what error is occurring. Thank you for your help in debugging this.

**Comment by Escaflow** [comment] 2018-01-06 20:04
Your welcome, happy to see some games for linux.

I will wait till next release and report back with a few logs if i can.

**Comment by mklingen** [comment] 2018-01-06 22:12
OK, I just tested on Ubuntu 14.04 and was able to reproduce (I think) the same issue.

The problem seems to be that the dwarfcorp binary is not properly linking against libpng15.so.15 within the executable directory. I was able to get this to work by inserting 

````
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:\`pwd`
````

in the script just before it executes DwarfCorp. Can you try something like that to see if it works?

**Comment by mklingen** [comment] 2018-01-06 23:40
Confirmed that same (or at least extremely similar) bug occurs on mac OSX. Fixed in a similar way. I honestly have no idea how this ever worked!

**Comment by Escaflow** [comment] 2018-01-07 11:24
Nice exporting the install dir as lib path works.
DwarfCorp.sh:
`export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:$(dirname `which $0`)"`

there is still a error message
`libpng error: bad adaptive filter value`

Fun fact to note, Saves without LD_LIBRARY_PATH set show a pic in the load menue but not these saved with it set to install dir.

**Comment by mklingen** [comment] 2018-01-07 16:01
There is an error message but it manages to load anyway?

**Comment by mklingen** [comment] 2018-01-07 21:04
I'm prepared to close this issue as soon as the next release is out. Hopefully it has been settled.

**Closed** 2018-02-04 16:32 UTC
Labels: Bug, Cross-Platform, Saving/Loading
