### ISSUE TITLE
Some items not being added to "gather" tasks

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#272] opened 2017-09-28 16:10 UTC
Not sure why, but I just had my dwarf do an initial sweep of trees and grain to get me started on a base and I did something that made them not gather at all (follow/ control).
So, then I had to directly command the axedwarf to gather the wood/apples/grain. Well, I noticed a bit later that after the dwarf went back to "look interesting," there were still quite a bit of the items not gathered.
When I went back to do another gather command, most of the items were selected properly, but some of them were not (and for no obvious trend of reasons).

GIF:
![gather bullshit](https://user-images.githubusercontent.com/22550054/30977729-4a8de1e0-a42d-11e7-8c09-1632cfb53532.gif)

**Comment by mklingen** [comment] 2017-09-28 16:44
Try unpausing the game... it might be that it doesn't work when paused

**Comment by Blecki** [comment] 2017-09-28 17:02
Sometimes items can be unselectable when they overlap exactly, as well. This is a known issue with no obvious solution just yet.

**Comment by Orangicus** [comment] 2017-09-28 18:15
I only pause so that I don't have to keep track of my game while I'm still trying to -play- the game. I don't play testing games. when I was selecting the items originally, the game was unpaused.

**Comment by mklingen** [comment] 2017-09-28 18:52
@Blecki here it seems they're selectable but no gather tasks are getting assigned (or they're immediately being invalidated)

**Comment by Orangicus** [comment] 2017-09-29 00:51
To be fair, he just cut down probably ten trees and ten bits of grain, so it might have hit a previously unknown limit (possibly 64?) to gather task quantity. I can safely say there could easily have been 64 things I set to gather.

**Comment by BombBloke** [comment] 2017-09-29 01:53
I've established triple-digit gather orders. I doubt quantity is related to what you're seeing here.

Did this occur after loading a save?

What happened to the items? Were you able to have another dwarf collect them, for example?

**Comment by Orangicus** [comment] 2017-09-29 02:16
> I've established triple-digit gather orders. I doubt quantity is related to what you're seeing here.

Noted.

> Did this occur after loading a save?

Nope. New game and played for a bit.

> What happened to the items? Were you able to have another dwarf collect them, for example?

The items were never collected? Shortly afterward, I moved my stockpile / balloon port / treasury around and experienced a bug which made the save unplayable (selection issue on reload).

**Comment by mklingen** [comment] 2017-09-29 13:28
Dwarfs have an inventory of 128 items. It's possible they aren't clearing their inventory properly.

**Comment by mklingen** [comment] 2017-09-30 20:17
scratch that, dwarves can have an unlimited number of items now. Not sure why this bug occurs. Will keep an eye on this issue as I can't reproduce it.

**Comment by mklingen** [comment] 2017-10-07 15:53
probably duplicate of #314 . I believe this has been fixed but will re-open the issue if it occurs in the next build.

**Closed by mklingen** 2017-10-07 15:53 UTC
Labels: AI, bug
