### ISSUE TITLE
Settings / Camera: Low terrain draw distance causes terrain tiles to pop when camera zoomed

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#574] opened 2018-03-19 20:59 UTC
Settings> Graphics> Turn terrain draw distance to low.

Switch to a top-down view of game. Zoom out to see terrain art pop out. Zoom in to see terrain pop in. Might be a culling issue?

Version: 13a3b20d

**Comment by mklingen** [comment] 2018-03-20 13:53
This is the intended behavior. What was the expected behavior on your part?

**Comment by com1clyf3** [comment] 2018-03-20 17:07
I suppose it's essentially design dissonant. With slicing the player is incentivized to play with the Z-axis, and learns they can have quite a lot of depth underground. Even though camera zoom and slice are different, thematically they're part of the same mechanic, and so when the player can't go more than a few (perceived) slices above their terrain patch without it texture popping, this means they're discouraged from playing above ground. More over, it makes play more difficult above ground when you can only view it up close.

X & Y-wise, the setting makes sense. But yeah, might want to adjust for Z.

**Comment by mklingen** [comment] 2018-03-20 17:23
okay, fair enough, we will change this calculation to a 2D one.

**Comment by mklingen** [comment] 2018-03-24 18:26
This has been fixed. Will be in next release (not 03.24)

**Comment by mklingen** [comment] 2018-03-25 14:05
Now in hotfix.

**Closed by mklingen** 2018-03-25 14:05 UTC
Labels: Art, Design (devs), GUI
