### ISSUE TITLE
AI: Making/destroying stockpiles causes AI loop

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#762] opened 2018-06-05 17:15 UTC
Reported on Discord:
![image](https://user-images.githubusercontent.com/6562812/40991722-ae51b986-68c2-11e8-86be-fbe2f70f54d6.png)

![image](https://user-images.githubusercontent.com/6562812/40991746-c458f14a-68c2-11e8-8ce0-07d7a8267669.png)

They're not totally sure what causes it, but it appears to have something to do with the AI not recognizing the right stockpile after a player has made and destroyed them several times.

A save and world was provided:

[hikeswake_theworldofbuggedstockpiles.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2073314/hikeswake_theworldofbuggedstockpiles.zip)
 
Version": "18.05.13_XNA"

**Comment by com1clyf3** [comment] 2018-06-05 18:08
Seems very likely this is a variation on #754  Both times the user has only seen this occurring on crafters. 

![image](https://user-images.githubusercontent.com/6562812/40994248-bd8c445a-68c9-11e8-9caa-9d8d3269b2ed.png)
[NeyorLand.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2073478/NeyorLand.zip)


They provided another save:
[NeyorLand.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2073479/NeyorLand.zip)

8549ba58

**Comment by mklingen** [comment] 2018-06-05 18:45
Ok, will try to reproduce when I have time.

**Comment by ToXeye** [comment] 2018-06-06 12:48
[log.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2076256/log.txt)

**Comment by mklingen** [comment] 2018-06-08 01:10
Managed to reproduce and fix from the Neyorland save.

Forensics:
1. Craftsdwarf is assigned 3 stockpile tasks that are impossible. It's bizarre because they appear to have been cancelled, but the dwarf still has access to them.
2. All dwarfs have impossible stock tasks assigned to them.

I put in some sanity checks at the task assignment/validation level to prevent both of these issues, and the dwarves got out of their rut. Fix is in master and will be in the next release.

**Closed by mklingen** 2018-06-08 01:10 UTC
Labels: AI, Build
