### ISSUE TITLE
Crash - When selecting a turret trap.

### ISSUE THREAD

**Issue by Haust891** [CompletelyFairGames/dwarfcorp#800] opened 2018-07-21 15:58 UTC
My latest crashlog, i've only got the one save so it should be the one crash that occurred when i selected a turret trap.

DwarfCorp Version 18.07.08_XNA
OS Version: 6.2.9200.0
OS Platform: Win32NT
OS SP: 
OS Version String: Microsoft Windows NT 6.2.9200.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at DwarfCorp.WrangleTool.<>c__DisplayClass2_0.<CanCatch>b__1(AnimalPen pen) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Scripting\Player\Tools\WrangleTool.cs:line 56
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at DwarfCorp.WrangleTool.CanCatch(Body animal, Boolean print) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Scripting\Player\Tools\WrangleTool.cs:line 56
   at DwarfCorp.ContextCommands.WrangleCommand.CanBeAppliedTo(Body Entity, WorldManager World) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\ContextCommands\ChopCommand.cs:line 63
   at DwarfCorp.GameStates.PlayState.<>c__DisplayClass69_0.<BodySelector_LeftReleased>b__1(ContextCommand c) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\PlayState.cs:line 2415
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at DwarfCorp.GameStates.PlayState.<BodySelector_LeftReleased>b__69_0(Body b) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\PlayState.cs:line 2415
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at DwarfCorp.GameStates.PlayState.BodySelector_LeftReleased() in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\PlayState.cs:line 2415
   at DwarfCorp.BodySelector.OnLeftReleased.Invoke()
   at DwarfCorp.BodySelector.Update() in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Scripting\Player\BodySelector.cs:line 240
   at DwarfCorp.GameMaster.UpdateInput(DwarfGame game, DwarfTime time) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Scripting\Player\GameMaster.cs:line 632
   at DwarfCorp.GameMaster.Update(DwarfGame game, DwarfTime time) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Scripting\Player\GameMaster.cs:line 447
   at DwarfCorp.WorldManager.Update(DwarfTime gameTime) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\World\WorldManager.cs:line 553
   at DwarfCorp.GameStates.PlayState.Update(DwarfTime gameTime) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\PlayState.cs:line 350
   at DwarfCorp.GameStates.GameStateManager.Update(DwarfTime time) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\GameStateManager.cs:line 117
   at DwarfCorp.DwarfGame.Update(GameTime time) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\DwarfGame.cs:line 474
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at DwarfCorp.Program.Main(String[] args) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Program.cs:line 89

**Comment by mklingen** [comment] 2018-07-21 18:17
This bug is caused by the universal selector tool. It occurs when 1) the player has built an animal pen and 2) they have selected anything that is not a creature. Fix underway.

**Comment by mklingen** [comment] 2018-07-21 18:19
Fix is now in master and will be in the next release.

**Closed by mklingen** 2018-07-21 18:19 UTC
Labels: Crash
