### ISSUE TITLE
Zoning Irregularities

### ISSUE THREAD

**Issue by BombBloke** [CompletelyFairGames/dwarfcorp#257] opened 2017-09-28 05:24 UTC
Branching off from #241:

* A "zone" may not be recognised by the game, seemingly at random, determined at time of construction. For example, a newly-constructed stock may not be a valid target for item storage, or a newly created treasury may not be a valid target for gold (though they'll visually appear to be proper zones). Haven't reproduced with other zone types, but haven't really tried. A new zone may be constructed on top of bugged ones as many times as is needed to produce a "valid" one - valid zones can't be re-zoned in this manner.

* Ordering zones adjacent to an existing unfinished order may result in a builder completing them all at once, as if they were one large order, but doing so in the time it should take to complete just the first. If multiple zone types are layed out in this manner, they'll all be converted to the type of the initial order. [See video](https://www.youtube.com/watch?v=cYuyWTGPzfc).

* Ordering zones of the same type next to existing completed orders doesn't seem to merge them. For example, a high-level dwarf may get stuck in the middle of a small treasury because it doesn't contain enough $ to pay him (which is another issue, seems he should take as much as possible and then search other treasuries for the rest...), and expanding the room out with a directly adjacent treasury zone won't resolve that, even if the new area is filled with loot. He must be manually ordered to move into the "new" treasury before he'll collect any money, and he may then get stuck in the "smaller" one again the next day.

**Comment by mklingen** [comment] 2017-10-01 00:51
For now I've just turned off merging of zones completely (that was unintentional), but it should definitely be put into the game.

**Comment by mklingen** [comment] 2017-10-21 21:30
Fixed by this commit https://github.com/CompletelyFairGames/dwarfcorp/commit/2754228b8ed29f006207f7a14765fbdd6a395669

It was actually caused by dwarf mining. If a dwarf mined a block while a room was being built, then the room would get a check that said "this room is empty! delete it!" but the room is not built yet, so it's empty, and hence gets deleted.

**Closed by mklingen** 2017-10-21 21:30 UTC
Labels: AI, Bug
