### ISSUE TITLE
Hang and Error upon load

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#278] opened 2017-09-28 20:32 UTC
With current HEAD, I load a file and the game hangs with a black screen for a couple of minutes. Then i crashes and in the eventlog I see the following error:
```
Application: DwarfCorp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at DwarfCorp.OctTreeNode`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(Microsoft.Xna.Framework.Vector3, Microsoft.Xna.Framework.Vector3)
   at DwarfCorp.OctTreeNode`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Subdivide()
   at DwarfCorp.OctTreeNode`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddToTree(System.Tuple`2<System.__Canon,Microsoft.Xna.Framework.BoundingBox>, Int32)
   at DwarfCorp.OctTreeNode`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddToTree(System.Tuple`2<System.__Canon,Microsoft.Xna.Framework.BoundingBox>, Int32)
   at DwarfCorp.OctTreeNode`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddToTree(System.Tuple`2<System.__Canon,Microsoft.Xna.Framework.BoundingBox>, Int32)
   at DwarfCorp.OctTreeNode`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddToTree(System.Tuple`2<System.__Canon,Microsoft.Xna.Framework.BoundingBox>, Int32)
   at DwarfCorp.OctTreeNode`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddToTree(System.Tuple`2<System.__Canon,Microsoft.Xna.Framework.BoundingBox>, Int32)
   at DwarfCorp.OctTreeNode`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddToTree(System.Tuple`2<System.__Canon,Microsoft.Xna.Framework.BoundingBox>, Int32)
   at DwarfCorp.OctTreeNode`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddToTree(System.Tuple`2<System.__Canon,Microsoft.Xna.Framework.BoundingBox>, Int32)
   at DwarfCorp.OctTreeNode`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddToTree(System.Tuple`2<System.__Canon,Microsoft.Xna.Framework.BoundingBox>, Int32)
   at DwarfCorp.OctTreeNode`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddToTree(System.Tuple`2<System.__Canon,Microsoft.Xna.Framework.BoundingBox>, Int32)
   at DwarfCorp.OctTreeNode`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddItem(System.__Canon, Microsoft.Xna.Framework.BoundingBox)
   at DwarfCorp.CollisionManager.AddObject(DwarfCorp.IBoundedObject, CollisionType)
   at DwarfCorp.Body.set_GlobalTransform(Microsoft.Xna.Framework.Matrix)
   at DwarfCorp.Body.UpdateTransform()
   at DwarfCorp.Body.PropogateTransforms()
   at DwarfCorp.Body.Update(DwarfCorp.DwarfTime, DwarfCorp.ChunkManager, DwarfCorp.Camera)
   at DwarfCorp.Physics.Update(DwarfCorp.DwarfTime, DwarfCorp.ChunkManager, DwarfCorp.Camera)
   at DwarfCorp.ComponentManager.Update(DwarfCorp.DwarfTime, DwarfCorp.ChunkManager, DwarfCorp.Camera)
   at DwarfCorp.WorldManager.Update(DwarfCorp.DwarfTime)
   at DwarfCorp.GameStates.PlayState.Update(DwarfCorp.DwarfTime)
   at DwarfCorp.GameStates.GameStateManager.Update(DwarfCorp.DwarfTime)
   at DwarfCorp.DwarfGame.Update(Microsoft.Xna.Framework.GameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(System.Object, System.EventArgs)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(System.Object, System.EventArgs)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean)
   at Microsoft.Xna.Framework.Game.Run()
   at DwarfCorp.Program.Main(System.String[])
```

**Comment by mklingen** [comment] 2017-09-28 20:33
Need more information. Are you loading from a save file, or starting a new game?

**Comment by Aikhjarto** [comment] 2017-09-28 20:50
16 GB Memory and loading from a save file Juvenile Hills from the attached zip file.
[DwarfCorp.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1342308/DwarfCorp.zip)

**Comment by Blecki** [comment] 2017-09-29 00:12
Looks like it's infinitely subdividing the octtree.

**Comment by mklingen** [comment] 2017-09-29 00:24
@Blecki I think that would be stackoverflow, but it could also run out of heap. But 16 GB? seems unlikely.

**Comment by mklingen** [comment] 2017-09-30 17:01
was unable to reproduce, but I will leave this issue open.

**Comment by Aikhjarto** [comment] 2017-10-01 12:50
Maybe its again some localization problem with my German windows 7?

**Comment by mklingen** [comment] 2017-10-01 16:38
It's possible but also it could be something more fundamental that we haven't fixed yet.

**Comment by com1clyf3** [comment] 2018-04-25 17:32
@Aikhjarto Are you still experiencing this issue?

Closing for regression, but will re-open if we get a response.

**Closed by com1clyf3** 2018-04-25 17:32 UTC
Labels: Crash
