### ISSUE TITLE
Fog of war does not always work well when loading a world.

### ISSUE THREAD

**Issue by Solsund** [CompletelyFairGames/dwarfcorp#29] opened 2017-01-15 06:14 UTC
Two of my four worlds seem to freak out when loading a world from a save.  The tiles almost all seem covered by the fog of war.

![image](https://cloud.githubusercontent.com/assets/6342605/21960613/c283219c-dab6-11e6-8c4c-f9ef1128d152.png)

**Comment by mklingen** [comment] 2017-01-15 17:45
Good catch, this is caused by the chunk files storing fog of war data incorrectly. Should be an easy fix. I will work on it.

**Comment by Solsund** [comment] 2017-01-15 18:34
The world from the screenshot.

[Fog Save.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/706795/Fog.Save.zip)

**Comment by mklingen** [comment] 2017-01-15 18:48
Okay, I can reproduce the bug.

**Comment by mklingen** [comment] 2017-01-15 18:54
appears to have been caused by file writing, not reading. should be fixed by a PR I am about to do.

**Comment by Solsund** [comment] 2017-01-26 23:20
Turns out this wasn't caused by the saving system at all.  All values were properly saved and loaded exactly like they were supposed to be.

It was caused by the fact that when generating a world a Reveal call is done to clear out the overworld unless the Fog of War is turned off.  So saving with FoW off would leave the whole world set as unexplored.  Loading a world doesn't force a Reveal.

I've semi-hackishly fixed this by forcing world generation to do a Reveal even if Fog of War is turned off.  It's mostly the same as having that opening reveal done during game load except it put the extra wait time during creation where users are likely a bit more patient.

**Closed** 2017-02-03 17:43 UTC
Labels: bug, Saving/Loading
