### ISSUE TITLE
God menu is unusable in low res settings

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#713] opened 2018-05-14 23:18 UTC
Players using low res will have part of the god menu cut off. God menu currently pixel perfect.

061f6d5c

**Comment by mklingen** [comment] 2018-05-17 15:32
suggestion: add columns when the god menu gets too high.

**Comment by mklingen** [comment] 2018-05-19 21:11
Fixed in master.

**Comment by mklingen** [comment] 2018-05-29 19:52
Looks fine to me

**Comment by mklingen** [comment] 2018-05-29 19:53
Oh, you're missing two of the rows wtf

**Comment by mklingen** [comment] 2018-06-02 20:33
Ok, I have reproduced. The problem is that when the resolution of the screen changes, the underlying widgets don't change. Will need to get the god menu to reconstruct itself when it gets laid out.

**Comment by mklingen** [comment] 2018-06-02 20:51
Was incorrect. The problem was that the god menu was rendered behind the bottom bar. Fixed.

**Closed by mklingen** 2018-06-02 20:51 UTC
Labels: God Menu, config / settings
