### ISSUE TITLE
[BUG] game crashes when Steam Overlay is on. (Ubuntu 17.04, possibly other platforms)

### ISSUE THREAD

**Issue by Escaflow** [CompletelyFairGames/dwarfcorp#513] opened 2017-12-26 20:32 UTC
Game Wont Launch with Steam, its loading to Main Menu and dies there.
Log output:

> Game started at 12/26/2017 : 20:52
> GL_INVALID_ENUM in glMatrixMode(mode)
> 	Source: GL_DEBUG_SOURCE_API_ARB
> 	Type: GL_DEBUG_TYPE_ERROR_ARB
> 	Severity: GL_DEBUG_SEVERITY_HIGH_ARB

Latest Updates, Xorg gdm.

btw there is a error in the DwarfCorp.sh the libSDL2-2.0.so is under 
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so
but setting the right path don't change the Startup crash in Steam.

Running from sh works kinda.. the log file gets spammed with

> using glBufferSubData(buffer 54, offset 0, size 176) to update a GL_STATIC_DRAW buffer
> 	Source: GL_DEBUG_SOURCE_API_ARB
> 	Type: GL_DEBUG_TYPE_PERFORMANCE_ARB
> 	Severity: GL_DEBUG_SEVERITY_MEDIUM_ARB
 and after ~10min its about 300mb big.

It Crashed with the error:
> [ERROR] FATAL UNHANDLED EXCEPTION: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
>   at System.ThrowHelper.ThrowKeyNotFoundException () [0x00000] in <1170fb08300b4d0db71c1d1db8555768>:0 
>   at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00021] in <1170fb08300b4d0db71c1d1db8555768>:0 
>   at DwarfCorp.MoveObjectTool.Update (DwarfCorp.DwarfGame game, DwarfCorp.DwarfTime time) [0x0013e] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
>   at DwarfCorp.GameMaster.Update (DwarfCorp.DwarfGame game, DwarfCorp.DwarfTime time) [0x0001c] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
>   at DwarfCorp.WorldManager.Update (DwarfCorp.DwarfTime gameTime) [0x000ee] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
>   at DwarfCorp.GameStates.PlayState.Update (DwarfCorp.DwarfTime gameTime) [0x00050] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
>   at DwarfCorp.GameStates.GameStateManager.Update (DwarfCorp.DwarfTime time) [0x0007a] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
>   at DwarfCorp.DwarfGame.Update (Microsoft.Xna.Framework.GameTime time) [0x0002c] in <6c2498a22d7b4d10b30afa2777610d7e>:0 
> AL lib: (EE) alc_cleanup: 1 device not closed

(if i should open another Issue for that just note me)

Driver info:
IGLDevice: OpenGLDevice
OpenGL Device: AMD HAWAII (DRM 2.50.0 / 4.13.0-21-generic, LLVM 5.0.0)
OpenGL Driver: 3.0 Mesa 17.2.4
OpenGL Vendor: X.Org
MojoShader Profile: glsl120
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD HAWAII (DRM 2.50.0 / 4.13.0-21-generic, LLVM 5.0.0) (0x67b1)
    Version: 17.2.4
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1

if you need anything else let me know, im happy to help.

**Comment by mklingen** [comment] 2017-12-27 19:43
Sorry about that. I have recently tested using Ubuntu 14.04 and an nvidia graphics card. I have not tested with anything higher than Ubuntu 16 and AMD graphics card. What happens when you comment out the line that sets the SDL version to use? (that should just cause it to use whatever we shipped with).

2nd error (move object tool) seems unrelated.

**Comment by mklingen** [comment] 2017-12-27 19:51
First bug is occuring in Steam overlay. That explains why I haven't caught it yet -- it only occurs when the game has been launched from Steam. Will investigate.

**Comment by mklingen** [comment] 2017-12-27 19:52
Bug is the same as this one from SuperBloodHockey, also using FNA

https://steamcommunity.com/app/532190/discussions/2/1474221865199489315/?ctp=5

**Comment by mklingen** [comment] 2017-12-27 19:56
Spam about glBufferSubData probably means I'm using the wrong mode for a vertex buffer. Will make another issue for that.

**Comment by Escaflow** [comment] 2017-12-28 15:13
Disabling the Steam Overay does work, i Played it a bit by just starting the bin...
I think i can get addicted to this game once i can save/load my progress.

cheers man, keep it up!

**Comment by mklingen** [comment] 2018-01-01 21:20
Saving/loading doesn't work for you!?!

**Comment by Escaflow** [comment] 2018-01-06 18:56
Saving works, loading not.
Opened a new issue for that since its not working in Anny circumstance.

**Comment by mklingen** [comment] 2018-01-07 16:09
Possible this issue is related to #520 , since if LD_LIBRARY_PATH was not set correctly its possible that Steam Overlay doesn't play nicely.

**Comment by Escaflow** [comment] 2018-01-08 17:44
...and... still CTD with Steam Overlay.

**Comment by com1clyf3** [comment] 2018-04-26 21:50
@Escaflow  Are you still experiencing this issue?

Closing for regression. Will open in case of response.

**Closed by com1clyf3** 2018-04-26 21:50 UTC
Labels: Crash, Performance, Steam

**Comment by Escaflow** [comment] 2018-04-27 22:27
Ubuntu 18.04 starts without issue.
Sorry, forgot to check again for 17.10 before the update.
