### ISSUE TITLE
Dwarves idle, won't respond

### ISSUE THREAD

**Issue by Cathairez** [CompletelyFairGames/dwarfcorp#439] opened 2017-10-26 00:15 UTC
Dwarves won't gather, craft, mine, or build zones. They were going down to attack some mud golems at one point only to stop and face the wall until killed.

Canceling the task does nothing, it just reappears back. Exiting the game causes a crash.

Here's a link to my save.
[Featherland_629.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1416591/Featherland_629.zip)

**Comment by mklingen** [comment] 2017-10-26 12:59
Duplicate of #433

**Comment by Cathairez** [comment] 2017-10-26 13:02
:-(, hope the save is of some use

**Comment by mklingen** [comment] 2017-10-26 13:05
I will try it!

**Comment by mklingen** [comment] 2017-10-26 22:56
Thank you for this save. I can now easily reproduce this issue and will have to think hard about the correct fix. So this is caused by dwarfs having a Kill Entity task for an unreachable entity. When this happens, the dwarves continually re-plan. The A* thread gets clogged, and the game slows down since dwarves are unable to fulfill plan requests.

**Comment by mklingen** [comment] 2017-10-27 19:06
Okay, current plan for this: dwarves will always be moving toward their goal. If the plan fails, they continue moving in a greedy fashion and retry the plan later. They will never cancel pathfinding unless the player tells them to or a higher priority task overrides it. This way the plan thread isn't hogged, and the dwarves are always doing something readable to the player rather than just standing around.

**Comment by mklingen** [comment] 2017-10-28 12:11
Fixed in the recent build using my suggestion. Still not desirable but much better.

**Closed by mklingen** 2017-10-28 12:11 UTC
Labels: duplicate
