### ISSUE TITLE
craftsdwarves hang on walls instead of going to anvil's level

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#370] opened 2017-10-08 20:37 UTC
craftsdwarves prefer to hang on block edges to use anvils, build objects, etc. when it's closer than standing on the same level as the object. obviously hanging on walls is needed in some cases (building ladders, for example), but dwarves should prefer to stand on flat ground when possible.
also, when wall-hanging (on a ladder), the climbing animation plays instead of hammer-swinging.

**Comment by mklingen** [comment] 2017-10-12 15:35
Actually this is a duplicate of #390 because of the dwarf's concept of "adjacency" being too broad. It should probably be something like "Is less than 1 away from the target and is standing on a block"

**Comment by mklingen** [comment] 2017-10-15 23:20
Fixed by a recent change. Will test to make sure it doesn't happen.

**Closed by mklingen** 2017-10-15 23:20 UTC
Labels: AI, Bug
