### ISSUE TITLE
Mac: Game Crash at Launch

### ISSUE THREAD

**Issue by LRGitHubABC** [CompletelyFairGames/dwarfcorp#544] opened 2018-02-23 04:45 UTC
I have a MAC.  I launch the game.  I see the dwarf running and then I get a message saying something needs access to control my computer.  I choose cancel several times.  Then the game crashes and sends me back to the Steam page.

**Comment by mklingen** [comment] 2018-02-23 13:54
Um, did you try letting DwarfCorp have access to your computer?

**Comment by LRGitHubABC** [comment] 2018-02-23 14:52
Hi,

Well yes but it won’t accept our passwords.  I even had my friend try Incase I am missing something.  It is looking for a password we don’t have.

I know the game is early access.  Is there any protocol set up to walk us through?  I know many people have hit bumps.  I want to try to fix this otherwise it is not playable.


Sent from my iPhone,
Tina Rizzo

**Comment by LRGitHubABC** [comment] 2018-02-23 16:10
Hi Matthew,

Here is what I am seeing:

Launch the game….it is when “Creating Game Master” shows on the right side upper corner the following pops up….Developer Tools Access needs to take control of another process for debugging to continue.  Enter the name and password of a user in the Developer Tools group to allow this.

I am not sure what password but when I hit cancel it crashes out and goes to the Steam page.

Hopefully this helps.
Tina

**Comment by mklingen** [comment] 2018-02-23 16:49
Oh I see, it's actually crashing and asking to debug the process, not asking for access to a file or something. I will test on Mac soon (it's been a while). Possibly Macs just don't work at the moment.

In the meantime the most helpful thing you could do is run the game in the terminal to see what crashes it reports. Unfortunately automatic crash reporting also just doesn't work on Mac at the moment.

**Comment by LRGitHubABC** [comment] 2018-02-23 18:52
Hi Matthew,

Great.  Thanks.  Really sorry…but I am not tech savvy….what do you mean by ‘run the game in the terminal?  What do I do to get to the terminal?

Tina

**Comment by mklingen** [comment] 2018-02-23 19:19
Okay, don't worry about it, I will test tomorrow and see if I can reproduce. If not I can give instructions for how to run the game in a terminal.

**Comment by mklingen** [comment] 2018-02-24 18:50
Okay, FYI I just ran the game on OSX without issue. It's possible that something we've changed in the last few weeks has fixed the issue, or there is an unresolved issue that I am unable to reproduce.

So, it would be super helpful if you could do the following for me to collect info on this crash:
> 1. Open finder and look for "Terminal." Open the terminal application.
> 2. Type into the terminal `cd ~/Library/Application Support/Steam/SteamApps/DwarfCorp/` and hit Enter.
> 3. Type `bash ./DwarfCorp.app/Contents/MacOS/DwarfCorpFNA` and hit Enter.

This should launch the game, and if the game crashes it will hopefully print an error message to the terminal. These instructions aren't exact as I'm not totally sure exactly where DwarfCorp will be installed on your computer, but it should be in that location. You can browse to that location in Finder to confirm that DwarfCorp is actually installed there.

In the future we'll try to make our crash reporting system compatible with Mac so that your crashes get reported to us automatically. Right now, our crash reporting system only works for Windows, so we have to rely on users to report them to us.

**Comment by mklingen** [comment] 2018-02-24 18:53
https://github.com/CompletelyFairGames/dwarfcorp/issues/551

**Comment by LRGitHubABC** [comment] 2018-02-24 19:31
Okay got it.  I will definitely attempt to do this.  I probably won’t be able to until Monday.


Sent from my iPhone,
Tina Rizzo

**Comment by LRGitHubABC** [comment] 2018-03-02 15:33
Hey Matthew,

I have not forgotten about this.  I have been able to locate the file…however, there is something up that I think links to how my husband set up different users on our mac.  I need him to answer a couple questions for me and then I think I will be good to go to do the testing this weekend.

Just keeping you in the loop.

**Comment by LRGitHubABC** [comment] 2018-03-04 18:50
Hi Matthew,

Sadly, we cannot figure out the path.  My husband thinks Mac does something to ‘protect’ the computer which is not allowing in terminal the path we can see to get to Dwarf Corp actually follow it.  We keep getting path file directory not found.  

Thanks for trying to help us.  I think we have hit wall.

Tina

> Begin forwarded message:
> 
> From: Rizzo's <rizzos@mac.com>
> Subject: Re: [CompletelyFairGames/dwarfcorp] Mac: Game Crash at Launch (#544)
> Date: March 2, 2018 at 10:33:49 AM EST
> To: CompletelyFairGames/dwarfcorp <reply@reply.github.com>
> 
> Hey Matthew,
> 
> I have not forgotten about this.  I have been able to locate the file…however, there is something up that I think links to how my husband set up different users on our mac.  I need him to answer a couple questions for me and then I think I will be good to go to do the testing this weekend.
> 
> Just keeping you in the loop.
>

**Comment by mklingen** [comment] 2018-03-05 17:07
OK, don't worry about it. We will make crash reporting work better on Mac and hopefully in the future we will have a helpful error message on mac for this issue.

**Comment by LRGitHubABC** [comment] 2018-03-05 17:15
Thanks so much.  You have provided superb customer service.


Sent from my iPhone,
Tina Rizzo

**Comment by com1clyf3** [comment] 2018-04-26 22:13
@LRGitHubABC  Hi. Did this issue get resolved? I'm regressing open bugs, so trying t find out if I should close this issue. If you ever have any other issues, feel free to report them in a separate issue.

@mklingen Did you end up updating mac reporting?

**Comment by com1clyf3** [comment] 2018-04-27 02:15
#544 relevant

**Comment by com1clyf3** [comment] 2018-05-08 02:03
#551 got finished, so closing.

**Closed by com1clyf3** 2018-05-08 02:03 UTC
Labels: Crash, Mac
