### ISSUE TITLE
Dwarfs stuck in cycle when hungry and won't eat.

### ISSUE THREAD

**Issue by Sydonia** [CompletelyFairGames/dwarfcorp#523] opened 2018-01-10 13:31 UTC
I noticed that when a dwarf is farming and they become hungry frequently they will become stuck in a loop where they drop a food item and pick it up then drop another food item then pick it up. If you tell the dwarf not to gather the item they just dropped this breaks the loop and they eat and carry on. This issue is new to this update and I have only encountered it when harvesting from a farm.

**Comment by mklingen** [comment] 2018-01-16 11:27
I believe this is caused by hungry dwarfs attempting to eat from farms, but being denied due to the food being marked for restock. Instead they should be allowed to eat food whether its marked for restock or not.

**Comment by com1clyf3** [comment] 2018-04-26 21:59
Haven't observed this issue in more than a month. I think it got fixed sometime around #580 

Closing for regression.

**Closed by com1clyf3** 2018-04-26 21:59 UTC
Labels: AI
