### ISSUE TITLE
Treasury Weirdness

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#275] opened 2017-09-28 16:49 UTC
Okay. So.
1. Make treasury.
2. Move money from old treasury to new treasury.
3. Somehow fuck that up (money in the treasury wasn't being deposited into the treasury).
4. Delete treasury without new treasury.
5. Accidentally build stockpile in same place.
6. Dwarves stock that stockpile.
7. Notice and then delete that stockpile.
8. Replace with treasury (again).
9. Try to move stockpiled items off of treasury space with "gather" task.
10. "Gather" doesn't select items over the treasury?
11. [Edit] Can remove treasury; building a new treasury does not fix ungatherable drops.
12. MFW those items cannot be recovered.
13. Don't want to lose gold again, so I'm just going to leave it.
14. Save game and try to load to see what happens (if I can get those items).
15. MFW cannot select anything ever again on loading the game.
16. Ditch recovery efforts.
17. Glitched items aren't even destroyed by lava.

![fucking treasury](https://user-images.githubusercontent.com/22550054/30979477-993f80d2-a432-11e7-9ad1-1836344291dc.gif)

Yes, it's paused. Everything happens the same when unpaused.

**Comment by mklingen** [comment] 2017-09-28 20:37
Okay, seems related to some other issues. Will check it out this weekend.

**Comment by mklingen** [comment] 2017-09-30 20:16
Just want to say, this is really weird and I can't reproduce it. Will keep this issue open.

**Comment by Orangicus** [comment] 2017-10-01 03:38
After looking back, this might be related to #291 in which case it should be solved.
Cannot be certain, however, as I don't remember that well what I did to get this (the list I made doesn't result in this glitch).

**Comment by mklingen** [comment] 2017-10-21 21:29
Fixed by this commit https://github.com/CompletelyFairGames/dwarfcorp/commit/2754228b8ed29f006207f7a14765fbdd6a395669

It was actually caused by dwarf mining. If a dwarf mined a block while a room was being built, then the room would get a check that said "this room is empty! delete it!" but the room is not built yet, so it's empty, and hence gets deleted.

**Closed by mklingen** 2017-10-21 21:29 UTC
Labels: Bug
