### ISSUE TITLE
Dwarves freak out cutting trees sometimes.

### ISSUE THREAD

**Issue by Solsund** [CompletelyFairGames/dwarfcorp#16] opened 2017-01-10 06:36 UTC
Give a dwarf a tree to cut down and some of the time they will lose their mind and refuse to do any work at all until you cancel the command.  It appears to happen when you try to cut down a tree too close to another but I've had it happen with a tree in a clearing by itself.

When a dwarf gets this bug you can tell almost instantly because the dwarf will not be moving full speed but will almost appear to stutter, like he's accelerating then sliding to a stop over and over.  If it does get to a tree it will stop standing right next to it almost like it's stuck by Xeno's Paradox and can't cross that remaining distance.  If that poor dwarf has to jump up a block on the way to a tree they'll just quiver while touching the block.

It also sometimes appears that dwarves stuck in this loop do not fully accept their job because you can assign all four starting dwarves with "Chop" to a huge line of trees and multiple will attempt to cut down the same tree and lock up in this way instead of each one taking a different tree.

**Comment by mklingen** [comment] 2017-01-12 02:28
I can confirm this bug. I think its caused by the dwarves' AI trying to get to the *center* of the tree, but since dwarves are not tall enough for some trees, they can never reach the center and so just pause at the edge of the tree. It should be replaced instead by a condition that just says the dwarf has finished its path to the tree.

**Comment by mklingen** [comment] 2017-01-14 03:14
Same as #22, I think. Fixed by https://github.com/CompletelyFairGames/dwarfcorp/commit/4465694b67f7a8067447e446dffac33549f6c95c

**Closed by mklingen** 2017-01-14 03:14 UTC
Labels: bug
