### ISSUE TITLE
Art: "Shadow dwarves"/ Users report sightings of dwarf sprites vanishing/ The XNA minimize bug

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#897] opened 2018-10-10 15:48 UTC
Several steam users have reported seeing dwarf sprites vanish, leaving only their shadows, calling them "shadow dwarves", reminiscent of our re-occuring XNA problems. 

https://steamcommunity.com/app/252390/discussions/1/1730963192540672622/

This user reports it starting to occur an hour into the game.

Figured I'd make a bug for it, since we're working on it again.

**Comment by com1clyf3** [comment] 2018-10-10 15:58
#692

**Comment by mklingen** [comment] 2018-10-13 13:38
Closing as duplicate of #692.

**Closed by mklingen** 2018-10-13 13:38 UTC
Labels: A Bug, Art
