### ISSUE TITLE
UI: Changing res during tutorial will offset highlighted wireframe

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#748] opened 2018-05-29 17:46 UTC
![image](https://user-images.githubusercontent.com/6562812/40675714-7b935e40-6346-11e8-896f-405bc7c1528b.png)

1. Start new game.
2. Allow the tutorial to begin and highlight an area.
3. Change resolution.
4. Observe that the highlighted wire frame no longer aligns with the proper UI.

5c6a30a6

**Comment by mklingen** [comment] 2018-06-01 19:19
can reproduce but I am having trouble fixing. @Blecki do you want to take a look at it?

**Comment by Blecki** [comment] 2018-06-01 20:04
Sure.

What did you try? It just sets a text to hilite, doesn't it?

**Comment by mklingen** [comment] 2018-06-02 20:20
@Blecki issue I was having was that after resolution change, the highlighted widget's Rect property does not change.

**Comment by Blecki** [comment] 2018-06-02 20:45
It's because the GUI is rebuilt, so the reference is to a widget from the old GUI. Fix pending.

**Comment by Blecki** [comment] 2018-06-03 20:35
Fixed in blecki-dev. Took some serious changes, so you'll see the hilite behaving differently in general.

**Closed by Blecki** 2018-06-03 20:35 UTC
Labels: GUI, config / settings
