### ISSUE TITLE
Anims: Birds missing flapping wing animation

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#635] opened 2018-04-09 20:25 UTC
Vid: https://drive.google.com/open?id=1TG6buHf2BWy06StA6kYriw9A3u9lfeOG

Bird aren't flapping their wings when flying. See vid.

Save: 
[Cisaloia_647_131677790760883262.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1891670/Cisaloia_647_131677790760883262.zip)

World:
[Cisaloia.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1891674/Cisaloia.zip)

Version 37fcb4d2

**Comment by mklingen** [comment] 2018-04-09 20:31
huh. weird.

**Comment by com1clyf3** [comment] 2018-04-09 20:36
They're flapping in a new world I started, so it's definitely triggered by something.

**Comment by mklingen** [comment] 2018-04-09 21:59
Wow this was actually quite a rabbit hole. There were actually several bugs going on, all of which were caused by loading from a save.

1. The bird was loaded from a save while it was flying (pretty common scenario, I know). The "OverrideCharacterMode" flag was set, which prevented it from switching to a flying animation. Solution is to reset that flag.
2. Any `ActWrapperTask` like `Fly` is currently being loaded incorrectly. These types of tasks are throwaway tasks that aren't supposed to be saved. Solution was to bail out of these kinds of tasks when we detect they've been loaded from a save file.
3. Bird gravity was not being reset correctly. Solution was to set the bird's gravity correctly when it stops flying.

The combination of these bugs caused a floating zombie bird (actually a few of them in the save file) that had no tasks, and were just floating aimlessley and bouncing off the sides of the world.

Fixed in master.

**Closed by mklingen** 2018-04-09 21:59 UTC
Labels: Art
