### ISSUE TITLE
Cursor missing in "Money to trade"

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#409] opened 2017-10-16 21:11 UTC
Its quite random. While entering money to trade, I sometimes get a textcursor but most of the times i don't.

**Comment by mklingen** [comment] 2017-10-17 12:27
I don't understand. Can you clarify?

**Comment by Blecki** [comment] 2017-10-17 14:32
I think he means the | bar in between letters showing where you're typing. 

This is almost a duplicate of #256 - and the solution is the same. It's on my list.

**Comment by Aikhjarto** [comment] 2017-10-17 14:57
@Blecki yes, by "textcursor" i meant the vertical bar between the numbers.

**Comment by com1clyf3** [comment] 2018-03-19 16:24
Closed since dupe.

**Closed by com1clyf3** 2018-03-19 16:24 UTC
Labels: Duplicate
