### ISSUE TITLE
Low Repro Crash: Crash to desktop upon building an animal pen

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#878] opened 2018-10-02 21:23 UTC
Moments after the save in #877 , the game crashed. It seemed right after the crafter finished building an animal pen. 

Got a repro. It has to happen perfectly on its own. It's a super low repro, but it will happen. Maybe. Got it twice in a row anyways. 

If the other dwarves fight a demon, the crafter will path away. If they don't, the crafter will stay on their tasks and eventually crash the game when they build the animal pen behind the baloonport. Still searching for what exactly makes it occur, but this will work:

1. Load the save from #877 
2. Pause game and cancel attack on nearby demon (or else crafter gets new task)
3. Watch the crafter finish their zone, and then move on to the next zone behind the baloonport.
3.5 In the games where crafter does not move on to the animal pen, the game doesn't crash. When the task list is observed, the zone task is no where to be found.
4. Watch them finish building this zone. Observe crash to desktop.

No crash logs were produced.

e8d2312b

**Comment by mklingen** [comment] 2018-10-28 23:54
Even after reverting to e8d2312, I was unable to reproduce this crash. I'll try 4 more times and then if I'm unable to reproduce it I may close this issue since the saves are old enough now that they no longer work.

**Comment by mklingen** [comment] 2018-10-29 00:00
Okay, so I got *a* crash, but I'm not sure if it's related, it was #951 , which has already been fixed. EDIT: okay that crash happened two more times. I'm going to say this was #951, which was fixed.

**Closed by mklingen** 2018-10-29 00:00 UTC
Labels: A Bug, Build, Crash
