### ISSUE TITLE
suggestion: make food and trinket crafting less specific

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#374] opened 2017-10-08 20:41 UTC
- [ ] option to cook food with whatever is available, in addition to current system of specifying ingredients?
- [ ] in addition to current system of encrusting specific trinket with specific gem, have something like 'mass encrust' with more dropdowns: encrust [dropdown, default 'any quality'][dropdown for material] trinket with [dropdown, default 'any gem']

**Comment by mklingen** [comment] 2017-10-10 13:33
Basically we should just add "any" as an option to all the dropdowns right?

**Comment by plasticware** [comment] 2017-10-12 03:05
Well, you might want to encrust all your iron crafts, but not any of your wood crafts, or you might only want to encrust high-quality crafts, That's why I suggested those dropdowns.

For cooking, an 'any' dropdown would be perfect.

**Comment by mklingen** [comment] 2017-10-12 15:33
I see so you want to sort by material. Right now that's difficult because resources don't have a concept of material, and do not inherit properties based on what they're made of. I could mull it over and come up with a solution.

**Comment by com1clyf3** [comment] 2018-04-25 18:10
@mklingen This still sounds useful. Making not in prospectus and closing for regression. Feel free to re-open if you want to act on these though.

**Closed by com1clyf3** 2018-04-25 18:10 UTC
Labels: Design (devs)
