### ISSUE TITLE
QOL improvements + bugs

### ISSUE THREAD

**Issue by plasticware** [CompletelyFairGames/dwarfcorp#211] opened 2017-08-18 20:13 UTC
- [x] fired dwarves shouldn't take all inventory items with them, particularly money they've only picked up, rather than been paid
- [x] traders trying unsuccessfully to leave - maybe just have them disappear after a set amount of time
- [x] dwarves constantly reinfect each other with illnesses - maybe give them an immunity period after recovery?
- [x] super nitpicky, but loading screen doesn't seem to be exactly 2x scale - take a screenshot and zoom in. pixels are 2x2, 2x3, 3x3.
- [x] enlarge map icons when zooming in on minimap and world gen screens
- [x] have someone sell sand/glass? no way to get it other than mining it
- [x] since craftsdwarf goes back and forth between stockpile and forge, only grabbing enough materials for one trinket/brick/etc at a time, have him deposit trinkets/bricks/etc as he makes them, rather than hoarding all of them until he's done?
- [x] don't make 'paused' text block mouse? i feel like i should be able to click on things behind it. same for stockpile inventory at top of screen, possibly other gui widgets as well - anything that doesn't have a solid tray should not block clicks
- [x] make dwarves prefer eating cooked meals/ale over raw materials, to avoid harvesting plants and immediately eating them before having a chance to replant
- [x] increase water evaporation rate - rain kills the framerate and basically never recovers
- [ ] maybe snow should go away over time, too
- [x] when deleting rooms (treasury in my game), don't delete floor blocks and instead replace with plain blocks for floor - blue tile, brown tile, cobble, etc as appropriate
- [x] can't select bed in use by dwarf with move tool, which seems like correct behavior, but should give tooltip saying object is in use
- [x] craftsdwarf autonomously queues up many craft tasks, sometimes prioritized over player-assigned tasks - make them only queue up one at a time at most
- [x] bring back old system of having global pool of tasks, rather than assigning tasks to dwarves immediately, or at least consider dwarves' existing assigned tasks? example: craftsdwarf is busy making trinkets, all dwarves assigned to plant crops. miners plant theirs and stand around; craftsdwarf does not get around to planting his until much later.
- [x] let player know that objects can be rotated with r/t during initial placement, rather than only when using move/rotate tool

bugs:
- [x] numbers should draw in front of icons for stockpile contents at top of screen, rather than behind
- [x] (have music on) start a new game, open economy screen from icon in the top right immediately. after music intro, does not start playing looping portion. being in the trade screen also stops new music section from playing.
- [x] alt-scrolling does not let you make a selection two blocks high, skipping from 1 to 3, then every number afterward
- [x] planting tasks are forgotten overnight
- [x] when building objects, previewed item is not on current tile - updates correctly after using r/t to rotate object before attempting placement
- [x] when building turrets (possibly other objects, didn't try), can't build next to stockpiles, as it claims the boxes are occupying the tile - works correctly after using r/t to rotate object before attempting placement
- [x] when using move/rotate tool to move beds (possibly other objects, didn't try), have to rotate the bed before being allowed to actually move it somewhere else
- [x] wrangling does not work - no dwarf acts on the task
~~when placing objects, can place more only based on current stockpile inventory, not taking into account materials consumed by other placements - for example, with the starting 8 iron, build an anvil. while first one is being built and 4 iron remain in stockpile, can assign many more build orders~~ working as intended
- [x] when building blocks, the count in bottom button tray of remaining blocks does not update
- [x] trade: when you offer money, you instead get it
- [x] rounding error: fire two dwarves so you have 3, then build a stockpile, awarding $20. you actually get $20.01.
- [x] economy screen: click 'fire' button more than once, and more than one dialog appears
- [ ] noticeable framerate drop in economy screen, trade envoy dialog, trade screen

7abdc1e in mklingen_dev:
- [x] can no longer click-drag for planting - one dwarf will plant one thing, then stop. while planting, all other plant orders are ignored. 
- [x] craftsdwarf keeps trying to craft things when there aren't enough resources - task should be cancelled
- [x] after assigning crafter multiple items (e.g. craft 10 trinkets), the crafter will autonomously craft 10 when idle - should only craft 1x
- [x] things bought from trade envoy don't immediately show up in inventory - i think my original balloon port stockpile was full, but i had another one with empty space

cc30142 in master:
- [x] tried crafting more trinkets than i had resources for: craftsdwarf retries task and continues crafting indefinitely when more resources are provided. also, the trinkets created do not show up in stockpile inventory at top of screen - in fact, the counts for crafts can randomly go up and down.
to reproduce: new game, build anvil, craft 5 iron trinkets. after crafting the first one, craftsdwarf stands around in stockpile because there's only 1 iron left. spawn more with god tool, gather, and watch inventory at top of screen.
maybe just cancel craft orders when there aren't enough resources, and give a notification for the player?
- [x] placed more beds than i could build, then chopped down tree to gather more wood, but craftsdwarf does not retry task. i think in this case, craftsdwarf should reattempt, since construction pile does not go away.
- [x] dwarves will reserve tilled tiles and try to plant things in other dwarves' inventories, causing the task to never be finished. mining the tile and replacing it does not free it.
- [x] also, mining tilled soil does not drop anything
- [x] entering/exiting god mode tool should revert cursor
- [x] only happens sometimes, hard to reproduce - have two animal pens, wrangle two of one kind of animal, then one of another, before any animals are put into pens. the second animal type will say you need more pens, meaning the first two wrangles are each reserving one of the pens, though they're both the same animal.

- [x] multi-tile planting does not immediately reserve all tiles, allowing more than one thing to be planted on tiles. with starting four workers, plant on 3x3 area - only four tiles are reserved, and can keep issuing more plant orders on other tiles - not fixed in 7d6092a.

7d6092a:
new crash:
- [x] purple screen on dwarfrunner screen, then black screen, then crash
Minimap.cs line 184
cameraToTarget.Normalize();
{"Begin cannot be called again until End has been successfully called."}

bugs:
- [x] bug with not being able to use the first built stockpile still sometimes occurs. no idea how to reproduce. 
- [x] cancelling building an item while it is in progress results in no refund and build completing with no object appearing at the end.
- [x] the previews for building a bed rotating before clicking to place are misleading - move cursor towards a wall to rotate preview, then move back away from wall and place to see.
~~ladders can be rotated in tile adjacent to wall so that they float in midair - after placing a ladder this way, subsequent ladders will not automatically rotate to face walls.~~ working as intended
- [ ] balloon port ladders not oriented correctly when appearing with two or more neighboring blocks.
- [x] could you possibly make it so that dwarves prefer to stand on flat surfaces rather than hang off walls when stocking stockpiles?
- [x] craft task failure should say something like "not enough resources" rather than "it is impossible".
- [x] dig tool reveals hidden caverns because fog of war is not treated as solid block.
- [x] mousing over grouped items in top-of-screen inventory does not always give breakdown. try spawning some different animals and killing them - only shows one kind of meat, one kind of bone, one kind of meal from those meats, one craft, etc. 

first steam release:
- [x] drag out some blocks to build, but before releasing the mouse, hit escape. can no longer build blocks, and selection grid does not go away.

moved to #359:
~~-some music transition issues - for example, trade envoy arriving at night means night music->faction music->day music. sometimes, music stops altogether.
-should probably get rid of god-mode generic items, like spawn "trinket" or "gem-encrusted trinket" or "meal", and have "rand bone" or rand meat" instead of generics.
-craftsdwarves like to hang on the edges of blocks to use anvils. possibly other items, too (cooking table, brewing still, etc.). 
edit: actually, hanging on edges can happen for anything dwarves need to stay still for, including building objects. obviously hanging on walls is needed in some cases (building ladders, for example), but dwarves should prefer to stand on flat ground when possible.
-clicking 'continue' from the dialog that pops up on pressing escape always unpauses the game, even if it was paused before pressing escape - game should remember original state when exiting dialog, and maybe change button text to 'back to game'.
-can use unpause key while 'escape' dialog is active - unpausing should close the dialog.
-apples and berries should probably not stack together in stockpile inventory.
-start a new game, pause, then disable and close the tutorial. when unpausing, another tutorial window will open.
-possible improvement: since chair's facing is not easy to tell when building, and it does have the minor visual effect of determining which direction dwarves eat food from, add something like an arrow on the ground to show orientation when rendering chair 'blueprints'?
-option to cook food with whatever is available, in addition to current system of using specific ingredients?
-option to select crafts to encrust by material (wood, stone, iron, etc.) in addition to current system of specific individual trinkets?~~

**Comment by mklingen** [comment] 2017-08-22 12:53
> when placing objects, can place more only based on current stockpile inventory, not taking into account materials consumed by other placements - for example, with the starting 8 iron, build an anvil. while first one is being built and 4 iron remain in stockpile, can assign many more build orders

Not sure this is a bug, more just a confusing feature. You're supposed to be able to queue up construction tasks. I think the real bug is that any building can be "disabled" because of lack of resources at all.

> rounding error: fire two dwarves so you have 3, then build a stockpile, awarding $20. you actually get $20.01.

Lol each dwarf gets $6.66, but that should come out to $19.98. I think what's really going on is the money is getting cast to a float, redivided and then cast to an int again.

**Comment by Blecki** [comment] 2017-08-23 23:59
>  increase water evaporation rate - rain kills the framerate and basically never recovers
Actually evaporation was disabled entirely. Re-enabled on my branch; probably needs tweaks.

> super nitpicky, but loading screen doesn't seem to be exactly 2x scale - take a screenshot and zoom in. pixels are 2x2, 2x3, 3x3.
The loading screen minigame is a pile of garbage. I hacked it together one evening while in the hospital (no joke). Going to rewrite or remove it.

> don't make 'paused' text block mouse? i feel like i should be able to click on things behind it. same for stockpile inventory at top of screen, possibly other gui widgets as well - anything that doesn't have a solid tray should not block clicks
This is actually trickier than it appears as making them transparent to clicks is at odds with having them show tooltips on mouse hover. Could possibly alphamask them but that is expensive. Might need a new type of behavior that lets clicks through but still shows tooltips, but that could be equally strange.

**Comment by mklingen** [comment] 2017-08-24 00:41
Alternatively we can move the "Paused" display elsewhere or draw it not as a widget.

**Comment by Blecki** [comment] 2017-08-27 21:16
> craftsdwarf autonomously queues up many craft tasks, sometimes prioritized over player-assigned tasks - make them only queue up one at a time at most

Believe I got this one. The tasks are queued when the dwarf has no active task - prevented them from being added when the dwarf has assigned incomplete tasks.

**Comment by mklingen** [comment] 2017-08-28 13:26
Got a bunch more this weekend on my branch. More to come later.

**Comment by Blecki** [comment] 2017-08-28 14:27
I'm working on the gui click through this week.

**Comment by mklingen** [comment] 2017-08-28 15:51
@Blecki I have fixed that already with a hack. Just set the size to (0, 0)

**Comment by Blecki** [comment] 2017-08-28 16:18
Do tooltips still work for the resources?

**Comment by mklingen** [comment] 2017-08-30 18:12
> loading crash in deserialize: fileutils.cs line 153, "Error converting value "{Min:{X:727.25 Y:21 Z:783.25} Max:{X:729.75 Y:23.75 Z:785.75}}" to type 'System.Nullable`1[Microsoft.Xna.Framework.BoundingBox]'. Path 

Okay, this is caused by wrangling. I will convert that from type Nullable to a boundingbox + bool struct.

**Comment by mklingen** [comment] 2017-09-01 00:29
Fixed the wrangling grammar and deserialize crash

**Comment by mklingen** [comment] 2017-09-04 11:30
Almost all of these done now. Snow melting -- that would require a heat system, something I would love to implement but would take a lot of time. Another hack might be to create entities which melt *new* snow generated by snowflakes.

Object placement -- still not sure if I want to do this. Maybe I will actually mirror the block placement system instead and just show the number that can be built with the current resources rather than disallowing placement.

**Comment by Vorgon1** [comment] 2017-09-08 10:24
Could put an automatic melting that is ~= to the rate snow falls in that area. That would provide a reason for the extra complication of snow melt runoff and creating rivers flowing down to the low areas and lakes. :)

Seasons would allow for snow across a wider range of the map but would also bring in the complications of growing seasons.

**Comment by mklingen** [comment] 2017-09-10 16:20
>craftsdwarf keeps trying to craft things when there aren't enough resources - task should be cancelled
 after assigning crafter multiple items (e.g. craft 10 trinkets), the crafter will autonomously craft 10 when idle - should only craft 1x

Fixed in my branch.

**Comment by mklingen** [comment] 2017-09-10 16:36
>  can no longer click-drag for planting - one dwarf will plant one thing, then stop. while planting, all other plant orders are ignored.

It looks like it takes a few seconds for dwarves to release the farm times. Still trying to understand why this is the case.

**Comment by Vorgon1** [comment] 2017-09-10 20:16
Didn't know if this should be a new thread or lumped with this one. It goes to one that is checked, sooo been fixed?

> bring back old system of having global pool of tasks, rather than assigning tasks to dwarves immediately, or at least consider dwarves' existing assigned tasks?

New game, selected everyone so they would stay bussy abit. Ordered some trees cut down, an area to be mined and an are to till. Axe guy should have gone to trees and then helped with tilling when done. Miners should have started digging, then helped with tilling if work left to do. Instead, everyone that can cut trees ran off to the trees, then started tilling while the axedrawf stood around. Then the craftdrawf stood around waiting for stone while the miners went to mine. Then 2 trade groups came but I had nothing to sell because which jobs they picked.

**Comment by Blecki** [comment] 2017-09-11 01:32
We've been discussing switching back to the 'pool of tasks' model but it's not going to happen before the next release.

I don't know if it would help much in this situation - when you issue the first chop command, there's not mine commands to take preference for the miners, so even using a task pool they are going to go chop down the tree first. We would have to allow new tasks to preempt active tasks, which brings a whole new set of issues with it. It would, however, mean that after chopping, the miners go to mine instead of till.

**Comment by Vorgon1** [comment] 2017-09-11 01:47
I set up all the orders in pause, so no one started anything until all orders were given. Another issue with the current system is hiring another dwarf, they won't start helping with current task until  you go through and repeat the orders for them. 

Also, When all the dwarfs went to tilling  I selected 1 and cancelled some of the tilling to get him to go start mining, but it cancelled for everyone. So it's kind of a hodge podge mix of pool orders and direct orders now kinda messed up for ether.

**Comment by mklingen** [comment] 2017-09-11 12:50
Some things (tilling, mining, planting, chopping) are pooled. Others (crafting) are not. We definitely should think about this system. Even when the game is paused all orders get assigned immediately, so that's why all the dwarves did things in that order. I will make a new issue for this.

**Comment by mklingen** [comment] 2017-09-11 12:54
https://github.com/CompletelyFairGames/dwarfcorp/issues/225

**Comment by Blecki** [comment] 2017-09-11 18:38
I'll be working on the task input interface once the pool model is restored. I'll likely work on the task assignment algorithm as well.

**Comment by Vorgon1** [comment] 2017-09-15 04:02
When Dwarfs have nothing to do, they seen to just stand around where ever the last job was or at the storage area after dropping off stuff. So you have to hunt them down to see what they are upto and they can be hard to see when hiding in the crates. Most DF type games have some area that can be set as an idle point. A place to go when they have nothing to do.

**Comment by mklingen** [comment] 2017-09-15 20:50
Dwarves currently will go to places where there are chairs to gather. Could also make them gather in other places.

**Comment by mklingen** [comment] 2017-09-22 01:06
Fixed the farming issue @plasticware

**Comment by mklingen** [comment] 2017-09-23 14:58
@plasticware fixed the crafting issue and notify users that dwarf can't craft it. Fixing the building issue will require a little more finesse but I think I can do it (basically the build task should always be retried until explicitly cancelled)

**Comment by mklingen** [comment] 2017-09-23 18:53
>  placed more beds than i could build, then chopped down tree to gather more wood, but craftsdwarf does not retry task. i think in this case, craftsdwarf should reattempt, since construction pile does not go away.

I can't seem to reproduce this. Looking at the code, the dwarf should be retrying (and does). I wonder if something else causes the task to get deleted.

**Comment by mklingen** [comment] 2017-09-23 18:59
Ah, I CAN reproduce it! It's caused by the dwarf thinking that there are available reasources because they are in another dwarf's inventory. This is tricky. I think I will remove the counting resources from within dwarf inventory because it appears to cause more trouble than its worth.

**Comment by mklingen** [comment] 2017-09-23 19:27
@plasticware okay this fixes the crafting object bug https://github.com/CompletelyFairGames/dwarfcorp/commit/307d1b3edef7ef3409cc5ff9ff96dfc80b667273

**Comment by mklingen** [comment] 2017-09-23 19:58
@plasticware I believe this fixes the farming bug https://github.com/CompletelyFairGames/dwarfcorp/commit/b2590f8439e93f42104aa442a82ff9118bc218b4

**Comment by mklingen** [comment] 2017-09-24 11:22
@plasticware  

> multi-tile planting does not immediately reserve all tiles, allowing more than one thing to be planted on tiles. with starting four workers, plant on 3x3 area - only four tiles are reserved, and can keep issuing more plant orders on the other assigned tiles. - not fixed in 7d6092a

While it appears like you're assigning plant orders, they immediately get rejected. The dwarf doesn't attempt to plant there because it is invalid. The tiles don't get reserved until a dwarf is moving toward the tile to farm it. I guess I could reserve them when the task gets assigned but there's no mechanism for doing something on task assignment atm.

**Comment by mklingen** [comment] 2017-09-24 11:25
> purple screen on dwarfrunner screen, then black screen, then crash
Minimap.cs line 184
cameraToTarget.Normalize();
{"Begin cannot be called again until End has been successfully called."}

Duplicate of the purple screen of death bug. It's tricky because somewhere, somehow the spritebatch is getting used in a thread which will randomly cause this error in random parts of the code.

**Comment by mklingen** [comment] 2017-09-24 13:28
@plasticware fixed crafting bug with this commit https://github.com/CompletelyFairGames/dwarfcorp/commit/aa86761e50de029675ed93d0278d2afba02864f2

**Comment by mklingen** [comment] 2017-09-24 13:51
dwarves hanging onto side of stockpiles fixed by this https://github.com/CompletelyFairGames/dwarfcorp/commit/8d00ca28bd59ce2d6f2386b45b7160af595ca4b4

**Comment by mklingen** [comment] 2017-09-24 13:56
more crafting info https://github.com/CompletelyFairGames/dwarfcorp/commit/d31ea859a948038a740f2ec4c551187af47f77f6

**Comment by mklingen** [comment] 2017-09-24 14:59
Fixed the craft rotations being misleading but this:

> ladders can be rotated in tile adjacent to wall so that they float in midair - after placing a ladder this way, subsequent ladders will not automatically rotate to face walls.

Is a "wontfix" because its a feature, not a bug. Once you rotate an object, subsequent placements will have the same rotation. This is to allow you to quickly line up rows of objects. If you want a ladder floating in midair, why not? It's still technically attached to the wall.

**Comment by mklingen** [comment] 2017-09-24 19:50
Fixed some of the other issues here. Thanks so much for all this comprehensive testing.

**Comment by mklingen** [comment] 2017-09-24 21:41
Multi-tile planting fixed. Can't reproduce wrangle bug.

**Comment by plasticware** [comment] 2017-09-25 04:37
another crash, after a few in-game days. 
just before this crash occurred, i also lost the ability to select objects (couldn't gather eggs or harvest plants), but that's probably a separate issue. 

System.NullReferenceException was unhandled
  _HResult=-2147467261
  _message=Object reference not set to an instance of an object.
  HResult=-2147467261
  IsTransient=false
  Message=Object reference not set to an instance of an object.
  Source=DwarfCorp
  StackTrace:
       at DwarfCorp.GeometricPrimitive.Render(GraphicsDevice device) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Graphics\Primitives\GeometricPrimitive.cs:line 132
       at DwarfCorp.WaterRenderer.DrawWaterFlat(GraphicsDevice device, Matrix view, Matrix projection, Shader effect, ChunkManager chunks) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Graphics\Effects\WaterRenderer.cs:line 213
       at DwarfCorp.Gui.Widgets.MinimapRenderer.PreRender(DwarfTime time, SpriteBatch sprites) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Gui\Widgets\Minimap.cs:line 184
       at DwarfCorp.GameStates.PlayState.Render(DwarfTime gameTime) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\PlayState.cs:line 354
       at DwarfCorp.GameStates.GameStateManager.Render(DwarfTime time) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\GameStateManager.cs:line 149
       at DwarfCorp.DwarfGame.Draw(GameTime time) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\DwarfGame.cs:line 339
       at Microsoft.Xna.Framework.Game.DrawFrame()
       at Microsoft.Xna.Framework.Game.Tick()
       at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
       at Microsoft.Xna.Framework.GameHost.OnIdle()
       at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
       at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
       at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at Microsoft.Xna.Framework.WindowsGameHost.Run()
       at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
       at DwarfCorp.Program.Main(String[] args) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Program.cs:line 71
  InnerException:

**Comment by Blecki** [comment] 2017-09-25 10:02
I think I got this crash; but just in case, I also made the water renderer eat all exceptions. Worse case, the water doesn't show up in the minimap for a frame or two - much better than crashing.

**Comment by mklingen** [comment] 2017-09-25 12:35
I thought I fixed that one :(

**Comment by mklingen** [comment] 2017-09-25 12:36
@Blecki that `VertexLock` is protecting the vertex buffer from being changed by an outside thread (for example by the chunks rebuilding or water rebuilding)

**Comment by Blecki** [comment] 2017-09-25 12:58
I already fixed it. The chunk rebuild no longer requires it, see my addition to liquid primitive. It's the only primitive that gets rebuilt in place so it's the only one that needs to be locked.

**Closed** 2017-10-08 20:31 UTC
Labels: bug, enhancement
