### ISSUE TITLE
InvalidOperationExceptionMicrosoft.Xna.Framework.Graphics.VertexBuffer in CopyData

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#322] opened 2017-10-03 22:36 UTC
DwarfCorp.GeometricPrimitive in ResetBuffer at line 211:21
Void ResetBuffer(Microsoft.Xna.Framework.Graphics.GraphicsDevice)
DwarfCorp.GeometricPrimitive in Render at line 121:21
DwarfCorp.LiquidPrimitive in Render at line 115:17
DwarfCorp.WaterRenderer in DrawWater at line 290:30
DwarfCorp.WorldManager in Render at line 890:13
DwarfCorp.GameStates.PlayState in Render at line 391:21
DwarfCorp.GameStates.GameStateManager in Render at line 149:29
DwarfCorp.DwarfGame in Draw at line 327:17

**Comment by Blecki** [comment] 2017-10-04 02:08
I can't reproduce but I have removed a potential race condition. Any more information on this one?

**Comment by mklingen** [comment] 2017-10-04 15:46
sorry, message was "The array is not the correct size for the amount of data requested."

My best guess here is that `Vertices` is getting changed in another thread (the one rebuilding water). I added a locking mechanism there to prevent that, but the lock is now gone. We should make sure that the vertex buffer is absolutely not get altered in another thread while the mesh is redrawing.

We can also catch this exception explicitly and refuse to draw when that's the case. Or at least do a little sanity check before drawing.

**Comment by com1clyf3** [comment] 2018-04-25 17:37
Linking this to performance tracking bug. #651  Closing for regression.

**Closed by com1clyf3** 2018-04-25 17:37 UTC
Labels: Performance
