### ISSUE TITLE
Herbivores randomly attack doors.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#506] opened 2017-12-16 20:29 UTC
Rabbits, birds, etc. attack doors randomly. Perhaps herbivores or other non-intelligent creatures should just consider doors obstacles.

**Comment by com1clyf3** [comment] 2018-04-26 20:51
I haven't observed this issue since joining the project. Closing for regression.

**Closed by com1clyf3** 2018-04-26 20:51 UTC
Labels: AI
