### ISSUE TITLE
No texture underneath blocks

### ISSUE THREAD

**Issue by ChainsawBaby** [CompletelyFairGames/dwarfcorp#232] opened 2017-09-22 07:58 UTC
I can see through walls, or something like that, when I'm viewing from a lower or same height as a block. See image
https://i.bratteng.me/w7grMY8gWO.png

**Comment by mklingen** [comment] 2017-09-22 12:51
Ooh nice catch. We actually don't draw the bottom of blocks to save GPU. We will need another pass at mesh generation to prevent this kind of thing.

**Comment by mklingen** [comment] 2017-10-01 19:19
possible duplicate of #238 and #298

**Comment by Blecki** [comment] 2017-10-01 20:20
I think this is working as intended. Block bottoms are culled. 

Shall I change that?

**Comment by com1clyf3** [comment] 2018-03-19 17:26
Sounds like fixed! Closed for now.

**Closed by com1clyf3** 2018-03-19 17:26 UTC
Labels: Bug, Performance
