### ISSUE TITLE
Dwarf can't find path back to food and starves

### ISSUE THREAD

**Issue by Kailan7401** [CompletelyFairGames/dwarfcorp#241] opened 2017-09-27 01:50 UTC
Axedwarf sent into tunnels to kill bats gets hungry. He stops moving and tries to get back to the stockpile to get food, but can't find his way so he just sits there. He overrides all my commands to move him back towards the stockpile manually and slowly starves to death (continuing to take health damage even when the game is paused).

**Comment by lemonrev** [comment] 2017-09-27 04:24
I have heard that the dwarves do not drop of everything after throwing just a few things in the inventory after collecting whatever you have told them to, Ie they will throw about 50% of whatever they collect back to the inventory or not even that unless you tell them directly to dump everything into the inventory space.

This is a massive bug and needs to be fixed.

**Comment by BombBloke** [comment] 2017-09-27 05:24
The stock bug doesn't appear to be related to pathing, but rather dwarves seem to just fail to recognise some stocks as a place to dump resources (so they hold on to stuff once all other stocks are filled). It's already mentioned in #211.

**Comment by mklingen** [comment] 2017-09-27 12:44
>  He overrides all my commands to move him back towards the stockpile manually and slowly starves to death

I think what's going on here is that "don't starve" is a higher priority than obeying the player commands, but "don't starve" is repeatedly failing due to pathfinding. In general there's a logical error in the way our AI is set up that pathfinding happens "lazily" -- they have no idea that a path exists until they try to plan a path. Will have to think carefully about how to address that problem.

> A similar issue occurs if a dwarf becomes trapped and there is no path back to base. If a miner digs down into a cave, say, and there's no way to climb back out, 

This should no longer be possible, unless the dwarf has dug through the ceiling of a cave and falls to the floor below.

**Comment by mklingen** [comment] 2017-09-27 12:45
> The stock bug doesn't appear to be related to pathing, but rather dwarves seem to just fail to recognise some stocks as a place to dump resources (so they hold on to stuff once all other stocks are filled). It's already mentioned in #211.

I haven't checked but I think right now the dwarf always tries to put resources in the nearest stockpile until it is full, then they go to the next one. Will have to test to see what's going on there.

**Comment by BombBloke** [comment] 2017-09-27 16:57
> In general there's a logical error in the way our AI is set up that pathfinding happens "lazily" -- they have no idea that a path exists until they try to plan a path. Will have to think carefully about how to address that problem.

It may be important to stress that the "dwarves getting stuck when wanting to go eat" issue occurs randomly, regardless as to whether a valid path is visible. FWIW, last I had this happen, I recall "draw paths" showed "target feasible" as "true".

> This should no longer be possible, unless the dwarf has dug through the ceiling of a cave and falls to the floor below.

I've encountered it this way, and also by (unintentionally) digging out blocks in the "wrong order" within a narrow underground tunnel. What's odd is that the dwarves won't move even if there's a clear path to whatever task it is they're trying to perform.

> I haven't checked but I think right now the dwarf always tries to put resources in the nearest stockpile until it is full, then they go to the next one. Will have to test to see what's going on there.

That's what happens when everything's working correctly, yes. However, it's quite possible to have an empty stock, idle dwarves which're still carrying items, and no actual stocking going on - the dwarves just stand around Looking Interesting until you build some more, forever ignoring the certain stores even if they're standing in them.

**Comment by mklingen** [comment] 2017-09-27 16:59
> That's what happens when everything's working correctly, yes. However, it's quite possible to have an empty stock, idle dwarves which're still carrying items, and no actual stocking going on - the dwarves just stand around Looking Interesting until you build some more, forever ignoring certain stores even if they're standing in them.

Yikes. Okay. Will try to reproduce. Any chance this happens after loading a save file? If so, that's critical information because many bugs only happen due to a problem with loading. I very rarely test games loaded from a save file, and its clear I need to do that more.

**Comment by BombBloke** [comment] 2017-09-27 17:48
I haven't tested the stock issue alongside the save system.

**Comment by mklingen** [comment] 2017-12-16 22:52
Likely duplicate of #433. Was fixed in two ways. One by improving pathfinding, and two, by allowing dwarfs to eat food that was marked for restocking.

**Closed by mklingen** 2017-12-16 22:52 UTC
Labels: AI, Bug
