### ISSUE TITLE
Farming issues

### ISSUE THREAD

**Issue by Sckiwi2018** [CompletelyFairGames/dwarfcorp#538] opened 2018-02-10 04:08 UTC
Several issues relating to farming mechanics. They seem to be somewhat random and can be worked around to a degree. I'm assuming these are errors and not some kind of mechanic for preventing reuse of the same soil continuously for planting. 

NB I don't think these are new issues - but I didn't see any reference to them in the Bug list. Apologies if I missed an existing filed issue.
[OlderSave.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1712994/OlderSave.zip)
[NewerSave.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/1712995/NewerSave.zip)

1) Refusal to Till Soil - despite the block being flagged to be tilled, nothing ever happens. Cancelling the order and then ordering a new till, has no effect.
2) Refusal to plant - Soil is tilled and ready to be planted. Order is given to plant, but nothing happens. Similar to (1) above. Again cancelling the original order and trying to plant again has no effect.
3) Not a Farm Error - Already tilled soil, which has already had crops planted, after harvesting the blocks come up with a message "Not a farm". Despite them blocks appearing to be tilled soil ready to be planted.

In all of the 3 above errors/issues digging out the soil, building a block of dirt, then re-tilling the soil usually allows the land to be used for crops again.

Two files attached in archive.
Older Save - you can see in the Apple Orchard both (3) 'Not a Farm' blocks, empty tilled blocks. Plus (1) Blocks marked for Tilling where nothing happens.
Newer Save - Still has (1) Blocks marked for tilling untilled. Plus within the Grain fields there are two blocks where (2) Refusal to plant occurs. There is still one block of (3) in the apple orchard but the others have been removed by digging out and replacing the blocks.

**Comment by mklingen** [comment] 2018-02-11 16:08
My hunch is that a dwarf has been assigned the tile and then somehow the farm task got cancelled or the dwarf died before his assignment  has been cleaned up. Will try to reproduce.

**Comment by mklingen** [comment] 2018-02-11 19:36
okay, I tracked down and fixed most of these issues. Thank you very much for the saves!

core issues: once a farm tile had been canceled by right clicking, it could never be uncancelled. changed the way farms get cancelled to fix that.

Also an instance of this bug #199 , since the farm tasks were all getting called "Farm x" where x is the location, there was no way to tell apart tilling, planting, etc. tasks.

Fix will be in the next build.

**Closed by mklingen** 2018-02-11 19:36 UTC
Labels: AI, Bug
