### ISSUE TITLE
Stuck in build tool

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#284] opened 2017-09-29 04:34 UTC
Select to build a stone door.
Cannot build stone door in my hallway even though the icon shows green (presumably meaning it can be built).
Try to cancel building the door.
Esc brings up main menu instead?
Close main menu- door still attached to cursor.
Try to initiate another task; door gives no fucks and is still on my cursor.

Save. Exit. Reload. Result:
![sdfsdfsd](https://user-images.githubusercontent.com/22550054/31000961-c6b006b0-a494-11e7-99e8-1a20fdeda21a.PNG)

**Comment by mklingen** [comment] 2017-09-29 13:33
Crash is duplicate of #251 

By cannot build you mean you can't place it? Or a dwarf refuses to do it?

**Comment by Orangicus** [comment] 2017-09-29 13:52
I was trying to place the door and it wouldn't even become a task. It was green to be placed but wouldn't set a construction kit.

**Comment by Orangicus** [comment] 2017-09-29 14:51
Seems to be unable to place the object because it's prioritizing rectangle selection instead.
![object shit](https://user-images.githubusercontent.com/22550054/31021498-e09e6ed0-a4ea-11e7-8072-5cf398e2e6a0.gif)

**Comment by mklingen** [comment] 2017-09-29 15:18
Looks like you're in the select tool, not the build tool, and that the build tool hasn't been properly canceled.

**Comment by mklingen** [comment] 2017-09-29 15:20
duplicate of https://github.com/CompletelyFairGames/dwarfcorp/issues/255

**Comment by mklingen** [comment] 2017-09-30 18:04
Fixed by https://github.com/CompletelyFairGames/dwarfcorp/commit/065444fd7ceae05bbbf05a771d9e320aee6f2394

**Closed by mklingen** 2017-09-30 18:04 UTC
Labels: bug
