### ISSUE TITLE
Zones: Building two different zones near terrain edge deselects blocks

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#666] opened 2018-04-24 19:49 UTC
This has a very specific repro. Like the other zone bug, it only happens on one specific side of planned zones. This will work with any combination of two zones and an edge on the left.

Vid: https://drive.google.com/open?id=1cnzQWUs6uHJf5_Mkk3UvOlIxO6unXCQu

Best to observe vid first.

1. Find an area of terrain with an edge that's on the "left"
2. Select one kind of zone and plan it four tiles away from the edge
3. Select a different kind of zone and plan it between edge and already planned zone
4. Observe that a third of the the second zone automatically deselects itself

cf2d71db

**Comment by mklingen** [comment] 2018-04-24 22:12
actually a duplicate of #665 , this can be reproduced by any zone which is built to the left of any other zone. It's been fixed in master.

**Closed by mklingen** 2018-04-24 22:12 UTC
Labels: Build
